In cluster-cups-config:   * /etc/init.d/cups status always returns 0, so require_cups() in     configure-athena-printers won't actually require cups.  Fix by just     calling start, since it's a noop if the service is already running.
git-svn-id: svn+ssh://svn.mit.edu/athena/trunk@25329 728af825-273c-0410-89f9-f7d3b574a069

diff --git a/debathena/config/cluster-cups-config/debian/configure-athena-printers b/debathena/config/cluster-cups-config/debian/configure-athena-printers
--- a/debathena/config/cluster-cups-config/debian/configure-athena-printers
+++ b/debathena/config/cluster-cups-config/debian/configure-athena-printers
@@ -51,11 +51,9 @@ require_cups() {
     else
         invoke="/etc/init.d/$rcname"
     fi
-    if ! /etc/init.d/$rcname status; then
-	if ! $invoke start; then
-	    echo "FATAL: Couldn't start CUPS!"
-	    exit 1
-	fi
+    if ! $invoke start; then
+	echo "FATAL: Couldn't start CUPS!"
+	exit 1
     fi
     if [ "$(lpstat -r)" != "scheduler is running" ]; then
       echo "FATAL: cups claimed to have started, but lpstat -r says it's not running!"
