In cluster-cups-config:   * Also do something useful with the printers.conf and classes.conf     files, and bail in the postinst/prerm if we can't stop CUPS while     attempting to do said useful thing. In cupsys-config:     other stuff while cups is down (or if we're not restarting it)
git-svn-id: svn+ssh://svn.mit.edu/athena/trunk@24838 728af825-273c-0410-89f9-f7d3b574a069

diff --git a/debathena/config/cluster-cups-config/debian/postinst b/debathena/config/cluster-cups-config/debian/postinst
--- a/debathena/config/cluster-cups-config/debian/postinst
+++ b/debathena/config/cluster-cups-config/debian/postinst
@@ -27,6 +27,13 @@ set -e
 
 restart_cups_extra()
 {
+    # CUPS needs to not be running while we do this.
+    if [ "$1" -gt 0 ]; then
+        echo "CUPS is running and cannot be stopped automatically!" >&2
+        echo "Please shut down CUPS and retry configuring this package." >&2
+        return 1
+    fi
+
     # Make a directory to back up the old printers/classes.conf if we
     # haven't previously done so.
     if ! [ -e /etc/cups/debathena-cluster-cups-config-saved ]; then
diff --git a/debathena/config/cluster-cups-config/debian/prerm b/debathena/config/cluster-cups-config/debian/prerm
--- a/debathena/config/cluster-cups-config/debian/prerm
+++ b/debathena/config/cluster-cups-config/debian/prerm
@@ -26,6 +26,13 @@ set -e
 
 restart_cups_extra ()
 {
+    # CUPS needs to not be running while we do this.
+    if [ "$1" -gt 0 ]; then
+        echo "CUPS is running and cannot be stopped automatically!" >&2
+        echo "Please shut down CUPS and retry deconfiguring this package." >&2
+        return 1
+    fi
+
     for file in printers.conf printers.conf.O classes.conf classes.conf.O; do
         if [ -e /etc/cups/"$file" ]; then
             rm /etc/cups/"$file"
