In cluster-cups-config:   * Ship an init script which can be used to add the printers at boot     time, since they can't be added at install time because CUPS isn't     running
git-svn-id: svn+ssh://svn.mit.edu/athena/trunk@25262 728af825-273c-0410-89f9-f7d3b574a069

diff --git a/debathena/config/cluster-cups-config/debian/postinst b/debathena/config/cluster-cups-config/debian/postinst
--- a/debathena/config/cluster-cups-config/debian/postinst
+++ b/debathena/config/cluster-cups-config/debian/postinst
@@ -28,6 +28,14 @@ set -e
 case "$1" in
     configure)
         restart_cups
+	if ! lpstat -r; then
+            # CUPS isn't running even though it should be.  We're probably
+            # inside the installer.  Let the initscript deal.
+	    touch /var/lib/debathena-cluster-cups-config-reconfigure_required
+	    touch /var/run/reboot-required
+	    echo "debathena-cluster-cups-config" >> /var/run/reboot-required.pkgs
+	    exit 0
+	fi
 	/usr/share/debathena-cluster-cups-config/configure-athena-printers add
     ;;
 
