Update pyhesiodfs to new version using python-hesiod
git-svn-id: svn+ssh://svn.mit.edu/athena/trunk@23151 728af825-273c-0410-89f9-f7d3b574a069

diff --git a/debathena/debathena/debathena-pyhesiodfs/debian/debathena-pyhesiodfs.init b/debathena/debathena/debathena-pyhesiodfs/debian/debathena-pyhesiodfs.init
--- a/debathena/debathena/debathena-pyhesiodfs/debian/debathena-pyhesiodfs.init
+++ b/debathena/debathena/debathena-pyhesiodfs/debian/debathena-pyhesiodfs.init
@@ -1,70 +1,130 @@
-#! /bin/sh -e
+#! /bin/sh
 ### BEGIN INIT INFO
-# Provides:             debathena-pyhesiodfs
-# Required-Start:	openafs-client
-# Required-Stop:        openafs-client
-# Should-Start:         $local_fs $network
-# Default-Start:	2 3 4 5
-# Default-Stop:         0 1 6
-# Short-Description:    Debathena automounter using pyFUSE
-# Description:          Auto-creates symlinks from /mit/LOCKER to AFS using Hesiod lookups.
+# Provides:          debathena-pyhesiodfs
+# Required-Start:    openafs-client
+# Required-Stop:     openafs-client
+# Should-Start:      $local_fs $network
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: Hesiod automounter for Athena lockers
+# Description:       Auto-create symlinks from /mit/LOCKER to AFS using Hesiod lookups.
 ### END INIT INFO
 
-PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin/:/usr/sbin:/usr/bin
-DAEMON="/usr/bin/pyhesiodfs"
+# Author: Evan Broder <broder@mit.edu>, Geoffrey Thomas <geofft@mit.edu>
+
+# Do NOT "set -e"
+
+# PATH should only include /usr/* if it runs after the mountnfs.sh script
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+DESC="Debathena /mit automounter"
 NAME=debathena-pyhesiodfs
+DAEMON=/usr/bin/pyhesiodfs
 pyhesiodfs_dir="/mit"
+DAEMON_ARGS="-f $pyhesiodfs_dir"
+PIDFILE=/var/run/$NAME.pid
+SCRIPTNAME=/etc/init.d/$NAME
 
-if [ -f /etc/default/pyhesiodfs ]; then
-  . /etc/default/pyhesiodfs
-fi
+# Exit if the package is not installed
+[ -x "$DAEMON" ] || exit 0
 
-# If the hesiod module hasn't been installed yet, this will fail and cause the
-# installation to fail, too. So fail silently instead
-if ! python -m hesiod >/dev/null 2>/dev/null
-then
-    exit 0
-fi
+# Read configuration variable file if it is present
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
+
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
+
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
+. /lib/lsb/init-functions
+
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+    # Return
+    #   0 if daemon has been started
+    #   1 if daemon was already running
+    #   2 if daemon could not be started
+    
+    # Try to make sure fuse is setup
+    [ -e /dev/fuse ] || modprobe fuse || return 2
+    
+    if cat /proc/mounts | grep " $pyhesiodfs_dir " >/dev/null 2>&1; then
+	return 1
+    fi
+    
+    mkdir -p "$pyhesiodfs_dir"
+    chown root:pyhesiodfs "$pyhesiodfs_dir"
+    chmod 770 "$pyhesiodfs_dir"
+    
+    start-stop-daemon --start --quiet --pidfile $PIDFILE \
+        --chuid pyhesiodfs:pyhesiodfs --background \
+        --make-pidfile \
+	--exec $DAEMON -- \
+        $DAEMON_ARGS \
+        || return 2
+}
+
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+    # Return
+    #   0 if daemon has been stopped
+    #   1 if daemon was already stopped
+    #   2 if daemon could not be stopped
+    #   other if a failure occurred
+    
+    if cat /proc/mounts | grep " $pyhesiodfs_dir " >/dev/null 2>&1; then
+        umount -l "$pyhesiodfs_dir" || return 2
+        # Many daemons don't delete their pidfiles when they exit.
+	rm -f "$PIDFILE"
+    else
+	return 1
+    fi
+}
 
 case "$1" in
-  start)
-	if start-stop-daemon --test --start --quiet \
-	    --pidfile "/var/run/$NAME.pid" \
-	    --startas "$DAEMON" -- -f "$pyhesiodfs_dir"
-	then
-	    modprobe fuse
-	    mkdir -p "$pyhesiodfs_dir"
-	    chgrp pyhesiodfs "$pyhesiodfs_dir"
-	    chmod g+w "$pyhesiodfs_dir"
-	    echo -n "Starting $DESC: "
-	    start-stop-daemon --oknodo --start --quiet \
-		--pidfile "/var/run/$NAME.pid" \
-		--chuid pyhesiodfs:pyhesiodfs --background \
-		--make-pidfile --startas "$DAEMON" -- -f "$pyhesiodfs_dir"
-	    echo "$NAME."
-	fi
-	;;
-  stop)
-	echo -n "Stopping $DESC: "
-	if start-stop-daemon --test --stop --quiet --pidfile "/var/run/$NAME.pid"
-	then
-	    fusermount -u "$pyhesiodfs_dir"
-	    echo "$NAME"
-	else
-	    echo "automounter for $pyhesiodfs_dir not running." >&2
-	fi
-	rm -f "/var/run/$NAME.pid"
-	;;
-  force-reload|restart)
-	"$0" stop
-	"$0" start
-	;;
-  *)
-	N=/"etc/init.d/$NAME"
-	# echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
-	echo "Usage: $N {start|stop|restart|force-reload}" >&2
-	exit 1
-	;;
+    start)
+        [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+        do_start
+        case "$?" in
+            0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+            2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+        esac
+        ;;
+    stop)
+        [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+        do_stop
+        case "$?" in
+            0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+            2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+        esac
+        ;;
+    restart|force-reload)
+        log_daemon_msg "Restarting $DESC" "$NAME"
+        do_stop
+        case "$?" in
+            0|1)
+                do_start
+                case "$?" in
+                    0) log_end_msg 0 ;;
+                    1) log_end_msg 1 ;; # Old process is still running
+                    *) log_end_msg 1 ;; # Failed to start
+                esac
+                ;;
+            *)
+                # Failed to stop
+                log_end_msg 1
+                ;;
+        esac
+        ;;
+    *)
+        echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
+        exit 3
+        ;;
 esac
 
-exit 0
+:
