Merge with OpenAFS 1.4.0-rc3.
git-svn-id: svn+ssh://svn.mit.edu/athena/trunk@22247 728af825-273c-0410-89f9-f7d3b574a069

diff --git a/third/openafs/configure b/third/openafs/configure
--- a/third/openafs/configure
+++ b/third/openafs/configure
@@ -1530,7 +1530,7 @@ fi
 
 PACKAGE=openafs
 
-VERSION=1.3.86
+VERSION=1.4.0-rc3
 
 if test "`cd $srcdir && pwd`" != "`pwd`" && test -f $srcdir/config.status; then
   { { echo "$as_me:$LINENO: error: source directory already configured; run \"make distclean\" there first" >&5
@@ -7745,6 +7745,74 @@ fi
 
 echo "$as_me:$LINENO: result: $ac_cv_linux_sched_struct_task_struct_has_exit_state" >&5
 echo "${ECHO_T}$ac_cv_linux_sched_struct_task_struct_has_exit_state" >&6
+CPPFLAGS="$save_CPPFLAGS"
+
+save_CPPFLAGS="$CPPFLAGS"
+CPPFLAGS="-I${LINUX_KERNEL_PATH}/include -I${LINUX_KERNEL_PATH}/include/asm/mach-${SUBARCH} -D__KERNEL__ $CPPFLAGS"
+echo "$as_me:$LINENO: checking whether refrigerator takes PF_FREEZE" >&5
+echo $ECHO_N "checking whether refrigerator takes PF_FREEZE... $ECHO_C" >&6
+if test "${ac_cv_linux_func_refrigerator_takes_pf_freeze+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <linux/sched.h>
+int
+main ()
+{
+
+refrigerator(PF_FREEZE);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_linux_func_refrigerator_takes_pf_freeze=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_linux_func_refrigerator_takes_pf_freeze=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+
+echo "$as_me:$LINENO: result: $ac_cv_linux_func_refrigerator_takes_pf_freeze" >&5
+echo "${ECHO_T}$ac_cv_linux_func_refrigerator_takes_pf_freeze" >&6
+if test "x$ac_cv_linux_func_refrigerator_takes_pf_freeze" = "xyes" ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define LINUX_REFRIGERATOR_TAKES_PF_FREEZE 1
+_ACEOF
+
+fi
 CPPFLAGS="$save_CPPFLAGS"
 
 if test "x$enable_redhat_buildsys" = "xyes"; then
