No, really, don't pass -A for Arch: any packages
git-svn-id: svn+ssh://svn.mit.edu/athena/trunk@25712 728af825-273c-0410-89f9-f7d3b574a069

diff --git a/debathena/scripts/da b/debathena/scripts/da
--- a/debathena/scripts/da
+++ b/debathena/scripts/da
@@ -23,6 +23,18 @@ prog="$1"; shift
 succ=
 fail=
 
+if [ $A -eq 1 ] && \
+    [ "${DA_SHOOT_SELF_IN_FOOT:-x}" != "yesplease" ]; then
+    for i in "$@"; do
+	if echo "$i" | grep -q '\.dsc$' && \
+	    grep -Fqx 'Architecture: any' "$i"; then
+	    echo "ERROR: Won't build an 'Architecture: any' package with -A" >&2
+	    exit 1
+	fi
+    done
+fi
+exit 0
+
 # Display a horizontal rule on stderr.
 hr () {
     for i in $(seq 60); do echo -n '═' >&2; done; echo >&2
