Don't build UNRELEASED packages
git-svn-id: svn+ssh://svn.mit.edu/athena/trunk@25578 728af825-273c-0410-89f9-f7d3b574a069

diff --git a/debathena/scripts/dasource b/debathena/scripts/dasource
--- a/debathena/scripts/dasource
+++ b/debathena/scripts/dasource
@@ -73,6 +73,13 @@ do_package() {
     svn co $repo/$pkgpath $dir
   fi
 
+  # Ensure that we're not trying to do something stupid
+  distribution=$(cd $dir && dpkg-parsechangelog | sed -n 's/Distribution: //p')
+  if [ "$distribution" = "UNRELEASED" ]; then
+    echo "You can't/shouldn't build a package marked as UNRELEASED."
+    exit 1
+  fi
+
   # Extract the changelog version and strip off the epoch and Debian component.
   changever=$(cd $dir && dpkg-parsechangelog | sed -n 's/Version: //p')
   sver=$(echo $changever | sed -re 's/^[0-9]+://p')
