- Don't die if grep-dctrl returns non-zero - Throw in an EXIT trap for future generations to provide some feedback   if we die
git-svn-id: svn+ssh://svn.mit.edu/athena/trunk@25512 728af825-273c-0410-89f9-f7d3b574a069

diff --git a/debathena/scripts/dasource b/debathena/scripts/dasource
--- a/debathena/scripts/dasource
+++ b/debathena/scripts/dasource
@@ -15,6 +15,8 @@
 
 set -e
 
+trap 'echo "dasource failed: Source package _not_ created"' EXIT
+
 die() {
   echo "$@" >&2
   exit 1
@@ -100,8 +102,8 @@ do_package() {
   # Read in debian-versions
   . $basedir/debian-versions.sh
 
-  NOBUILD=$(grep-dctrl -n -s X-Debathena-No-Build -F X-Debathena-No-Build -e . "$dir/debian/control")
-  BUILDFOR=$(grep-dctrl -n -s X-Debathena-Build-For -F X-Debathena-Build-For -e . "$dir/debian/control")
+  NOBUILD=$(grep-dctrl -n -s X-Debathena-No-Build -F X-Debathena-No-Build -e . "$dir/debian/control" || true)
+  BUILDFOR=$(grep-dctrl -n -s X-Debathena-Build-For -F X-Debathena-Build-For -e . "$dir/debian/control" || true)
   if [ -n "$NOBUILD" ] && [ -n "$BUILDFOR" ]; then
       echo "It is an error to specify both X-Debathena-Build-For and"
       echo "X-Debathena-No-Build.  Pick one and try again."
