Import pine 4.55.
git-svn-id: svn+ssh://svn.mit.edu/athena/branches/vendor@19275 728af825-273c-0410-89f9-f7d3b574a069

diff --git a/third/pine/contrib/ldap-setup b/third/pine/contrib/ldap-setup
--- a/third/pine/contrib/ldap-setup
+++ b/third/pine/contrib/ldap-setup
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: ldap-setup,v 1.1.1.2 2003-02-12 08:01:24 ghudson Exp $
+# $Id: ldap-setup,v 1.1.1.3 2003-05-01 01:12:55 ghudson Exp $
 #
 #            T H E    P I N E    M A I L   S Y S T E M
 #
@@ -21,7 +21,7 @@
 #   permission of the University of Washington.
 #
 #   Pine, Pico, and Pilot software and its included text are Copyright
-#   1989-2001 by the University of Washington.
+#   1989-2003 by the University of Washington.
 #
 #   The full text of our legal notices is contained in the file called
 #   CPYRIGHT, included with this distribution.
@@ -112,6 +112,16 @@ then
         else
 	  echo "/usr/lib/libldap.so not found"
 	fi
+      fi
+    elif [ "$1" = "Linux" -a "$btarget" = "lrh" ]; then
+      if [ -f /usr/lib/libldap.so ]; then
+	if [ -f /usr/include/ldap.h ]; then
+	  exit 3				# EXIT successfull
+	else
+	  echo "/usr/include/ldap.h not found"
+	fi
+      else
+	echo "/usr/lib/libldap.so not found"
       fi
     elif [ "$1" = "Darwin" ]; then
       set `echo $2 | tr "." " "`
