In archive-keyring:   * Use the standard debhelper postinst template.
git-svn-id: svn+ssh://svn.mit.edu/athena/trunk@23794 728af825-273c-0410-89f9-f7d3b574a069

diff --git a/debathena/debathena/archive-keyring/debian/debathena-archive-keyring.postinst b/debathena/debathena/archive-keyring/debian/debathena-archive-keyring.postinst
--- a/debathena/debathena/archive-keyring/debian/debathena-archive-keyring.postinst
+++ b/debathena/debathena/archive-keyring/debian/debathena-archive-keyring.postinst
@@ -1,8 +1,44 @@
 #!/bin/sh
+# postinst script for #PACKAGE#
+#
+# see: dh_installdeb(1)
 
-if hash apt-key >/dev/null 2>&1; then
-    apt-key add /usr/share/keyrings/debathena-archive-keyring.gpg
-    if apt-key list | grep -q A2DA1A6C; then
-        apt-key del A2DA1A6C
-    fi
-fi
+set -e
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+case "$1" in
+    configure)
+        if hash apt-key >/dev/null 2>&1; then
+            apt-key add /usr/share/keyrings/debathena-archive-keyring.gpg
+            if apt-key list | grep -q A2DA1A6C; then
+                apt-key del A2DA1A6C
+            fi
+        fi
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+exit 0
