Pick /var/mail or /var/spool/mail depending on which we find.
git-svn-id: svn+ssh://svn.mit.edu/athena/trunk@11531 728af825-273c-0410-89f9-f7d3b574a069

diff --git a/athena/bin/from/configure b/athena/bin/from/configure
--- a/athena/bin/from/configure
+++ b/athena/bin/from/configure
@@ -1462,6 +1462,24 @@ EOF
 fi
 
 
+echo $ac_n "checking for mail directory""... $ac_c" 1>&6
+echo "configure:1467: checking for mail directory" >&5
+if test -d /var/spool/mail; then
+	cat >> confdefs.h <<\EOF
+#define MAILDIR "/var/spool/mail"
+EOF
+
+	echo "$ac_t""/var/spool/mail" 1>&6
+elif test -d /var/mail; then
+	cat >> confdefs.h <<\EOF
+#define MAILDIR "/var/mail"
+EOF
+
+	echo "$ac_t""/var/mail" 1>&6
+else
+	{ echo "configure: error: can't locate mail spool directory" 1>&2; exit 1; }
+fi
+
 trap '' 1 2 15
 cat > confcache <<\EOF
 # This file is a shell script that caches the results of configure
