In reactivate:   * Try to kill remaining user processes using any of the login     chroot's bind mounts at session end.   * Don't die upon failure to umount any of the bind mounts at     session end; this should force a reboot after the umount of     the chroot mountpoint fails.
git-svn-id: svn+ssh://svn.mit.edu/athena/trunk@23458 728af825-273c-0410-89f9-f7d3b574a069

diff --git a/debathena/config/reactivate/debian/athena-login-snapshot b/debathena/config/reactivate/debian/athena-login-snapshot
--- a/debathena/config/reactivate/debian/athena-login-snapshot
+++ b/debathena/config/reactivate/debian/athena-login-snapshot
@@ -99,13 +99,22 @@ EOF
     ;;
 
   login-end)
-    # Clean up any processes using the mountpoint.
+    # Clean up any remaining user processes using the bind mounts.
+    if [ -n "$USER" -a "$USER" != root ]; then
+      for dir in $binddirs; do
+        su -s /bin/sh "$USER" -c "fuser -km /login$dir" > /dev/null || true
+      done
+    fi
+
+    # Clean up any processes using the chroot mountpoint.
     fuser -km /login > /dev/null || true
     sleep 2
 
     # Clean up the bind mounts we made earlier.
+    # If any of these fail, the umount of /login will fail below,
+    # and we will reboot.
     for dir in $binddirs; do
-      umount "/login$dir"
+      umount "/login$dir" || true
     done
 
     # Attempt to unmount /login.
