In msmtp-config:   * New debathena-msmtp script without -t and --debug and with better     handling of missing tickets.   * Include a debathena-msmtp-sendmail package that configures the     machine to use debathena-msmtp as its sendmail solution.
git-svn-id: svn+ssh://svn.mit.edu/athena/trunk@22899 728af825-273c-0410-89f9-f7d3b574a069

diff --git a/debathena/config/msmtp-config/debian/debathena-msmtp b/debathena/config/msmtp-config/debian/debathena-msmtp
--- a/debathena/config/msmtp-config/debian/debathena-msmtp
+++ b/debathena/config/msmtp-config/debian/debathena-msmtp
@@ -1,10 +1,16 @@
 #!/bin/sh
-if ! klist -s; then
-	echo "pine-sendmail: no valid Kerberos tickets found." >&2
+if [ -z "$DEBATHENA_SENDMAIL_AUTH" ]; then
+    if klist -s 2&>/dev/null; then
+	DEBATHENA_SENDMAIL_AUTH=yes
+    fi
 fi
-kuser=$(klist | sed -n 's/^Default principal: \(.*\)@.*/\1/ p')
-if [ -z "$kuser" ]; then
-	echo "pine-sendmail: no Kerberos tickets found." >&2
+if [ "$DEBATHENA_SENDMAIL_AUTH" = "yes" ]; then
+    kuser=$(klist 2>/dev/null | sed -n 's/^Default principal: \(.*\)@ATHENA\.MIT\.EDU/\1/ p')
+    if [ -z "$kuser" ]; then
+	echo "Could not find valid ATHENA.MIT.EDU Kerberos tickets." >&2
 	exit 1
+    fi
+    exec msmtp --host=outgoing.mit.edu --port=587 --auth=gssapi --user="$kuser" --auto-from=on --maildomain=mit.edu "$@"
+else
+    exec msmtp --host=outgoing.mit.edu --port=25 --auth=off --auto-from=on --maildomain=mit.edu "$@"
 fi
-exec msmtp --host=outgoing.mit.edu --port=587 --auth=gssapi --user="$kuser" --debug --auto-from=on --maildomain=mit.edu -t "$@"
