Import krb5 1.4.1.
git-svn-id: svn+ssh://svn.mit.edu/athena/branches/vendor@21888 728af825-273c-0410-89f9-f7d3b574a069

diff --git a/third/krb5/src/include/configure b/third/krb5/src/include/configure
--- a/third/krb5/src/include/configure
+++ b/third/krb5/src/include/configure
@@ -6407,6 +6407,112 @@ _ACEOF
   fi
 fi
 
+if test "$ac_cv_func_gmtime_r" = yes; then
+  echo "$as_me:$LINENO: checking whether gmtime_r returns int" >&5
+echo $ECHO_N "checking whether gmtime_r returns int... $ECHO_C" >&6
+  if test "${krb5_cv_gmtime_r_returns_int+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <time.h>
+   extern int gmtime_r ();
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+1;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  return_int=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+return_int=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+   cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <time.h>
+   extern struct tm *gmtime_r ();
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+1;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  return_ptr=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+return_ptr=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+   case $return_int/$return_ptr in
+     yes/no) krb5_cv_gmtime_r_returns_int=yes ;;
+     no/yes) krb5_cv_gmtime_r_returns_int=no ;;
+     *)      # Can't figure it out, punt the function.
+             ac_cv_func_gmtime_r=no ;;
+   esac
+fi
+
+  if test "$ac_cv_func_gmtime_r" = no; then
+    echo "$as_me:$LINENO: result: unknown -- ignoring gmtime_r" >&5
+echo "${ECHO_T}unknown -- ignoring gmtime_r" >&6
+  else
+    echo "$as_me:$LINENO: result: $krb5_cv_gmtime_r_returns_int" >&5
+echo "${ECHO_T}$krb5_cv_gmtime_r_returns_int" >&6
+    if test "$krb5_cv_gmtime_r_returns_int" = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define GMTIME_R_RETURNS_INT 1
+_ACEOF
+
+    fi
+  fi
+fi
+
 echo "$as_me:$LINENO: checking for getservbyname_r" >&5
 echo $ECHO_N "checking for getservbyname_r... $ECHO_C" >&6
 if test "${ac_cv_func_getservbyname_r+set}" = set; then
