Import gcc 3.4.3.
git-svn-id: svn+ssh://svn.mit.edu/athena/branches/vendor@21198 728af825-273c-0410-89f9-f7d3b574a069

diff --git a/third/gcc/maintainer-scripts/gcc_release b/third/gcc/maintainer-scripts/gcc_release
--- a/third/gcc/maintainer-scripts/gcc_release
+++ b/third/gcc/maintainer-scripts/gcc_release
@@ -64,12 +64,21 @@ inform() {
 
 usage() {
 cat <<EOF
-gcc_release     [-d destination]
-                [-u username]
-		[-r release]
-		[-t tag]
-		[-p previous-tarball]
-		[-s] [-f] [-l]
+gcc_release -r release [-f] [further options]
+gcc_release -s name:cvsbranch [further options]
+
+Options:
+
+  -r release           Version of the form X.Y or X.Y.Z.
+  -s name:cvsbranch    Create a snapshot, not a real release.
+
+  -d destination       Local working directory where we will build the release
+                       (default=${HOME}).
+  -f                   Create a final release (and update ChangeLogs,...).
+  -l                   Indicate that we are running on gcc.gnu.org.
+  -p previous-tarball  Location of a previous tarball (to generate diff files).
+  -t tag               Tag to mark the release in CVS.
+  -u username          Username for upload operations.
 EOF
     exit 1
 }
@@ -110,20 +119,25 @@ build_sources() {
     inform "Updating ChangeLogs and version files"
 
     ${CVS} co -d "`basename ${SOURCE_DIRECTORY}`" \
-           -r ${BRANCH} gcc || \
+           -r ${CVSBRANCH} gcc || \
            error "Could not check out release sources"
     for x in `find ${SOURCE_DIRECTORY} -name ChangeLog`; do
-      cat - ${x} > ${x}.new <<EOF
+      # Update this ChangeLog file only if it does not yet contain the
+      # entry we are going to add.  (This is a safety net for repeated
+      # runs of this script for the same release.)
+      if ! grep "GCC ${RELEASE} released." ${x} > /dev/null ; then       
+        cat - ${x} > ${x}.new <<EOF
 ${LONG_DATE}  Release Manager
 
-	* GCC ${RELEASE} Released.
+	* GCC ${RELEASE} released.
 
 EOF
-      mv ${x}.new ${x} || \
-        error "Could not update ${x}"
-      (changedir `dirname ${x}` && \
-        ${CVS} ci -m 'Mark ChangeLog' `basename ${x}`) || \
-        error "Could not commit ${x}"
+        mv ${x}.new ${x} || \
+            error "Could not update ${x}"
+        (changedir `dirname ${x}` && \
+            ${CVS} ci -m 'Mark ChangeLog' `basename ${x}`) || \
+            error "Could not commit ${x}"
+      fi
     done
 
     # Update `gcc/version.c'.
@@ -143,23 +157,44 @@ EOF
   fi
 
   # Tag the sources.
+  EXPORTDATE=""
   if [ -n "${TAG}" ]; then
-    inform "Tagging release sources"
-    ${CVS} rtag -r ${BRANCH} -F ${TAG} gcc || \
-      error "Could not tag release sources"
-    BRANCH=$TAG
+    inform "Tagging sources as ${TAG}"
+    ${CVS} rtag -r ${CVSBRANCH} -F ${TAG} gcc || \
+      error "Could not tag sources"
+    EXPORTTAG="-r${TAG}"
+  else
+    if [ ${CVSBRANCH} != "HEAD" ]; then
+      EXPORTTAG="-r${CVSBRANCH}"
+      # It does not work to use both "-r" and "-D" with
+      # "cvs export" so EXPORTDATE is not set here.
+    else
+      # HEAD is the default branch, no need to specify it.
+      EXPORTTAG=""
+      EXPORTDATE="-D`date -u +"%Y-%m-%d %H:%M"` UTC"
+    fi
   fi
 
   # Export the current sources.
-  inform "Retrieving release sources"
-  ${CVS} \
-       export -d "`basename ${SOURCE_DIRECTORY}`" \
-       -r ${BRANCH} gcc || \
-    error "Could not retrieve release sources"
+  inform "Retrieving sources (cvs export ${EXPORTTAG} ${EXPORTDATE} gcc)"
 
-  # Run gcc_update on them to set up the timestamps nicely.
+  if [ -z "${EXPORTTAG}" ]; then
+    ${CVS} export -d "`basename ${SOURCE_DIRECTORY}`" \
+       "${EXPORTDATE}" gcc || \
+      error "Could not retrieve sources"
+  elif [ -z "${EXPORTDATE}" ]; then
+    ${CVS} export -d "`basename ${SOURCE_DIRECTORY}`" \
+       "${EXPORTTAG}" gcc || \
+      error "Could not retrieve sources"
+  else
+    error "Cannot specify -r and -D at the same time"
+  fi
+
+  # Run gcc_update on them to set up the timestamps nicely, and (re)write
+  # the LAST_UPDATED file containing the CVS tag/date used.
   changedir "gcc-${RELEASE}"
   contrib/gcc_update --touch
+  echo "Obtained from CVS: ${EXPORTTAG} ${EXPORTDATE}" > LAST_UPDATED
 
   # Obtain some documentation files from the wwwdocs module.
   inform "Retrieving HTML documentation"
@@ -194,7 +229,7 @@ EOF
     ${SOURCE_DIRECTORY}/gcc/doc/install.texi2html
 
     # Regenerate the NEWS file.
-    contrib/gennews > gcc/NEWS || \
+    contrib/gennews > NEWS || \
       error "Could not regenerate NEWS files"
 
     # Now, we must build the compiler in order to create any generated
@@ -203,25 +238,16 @@ EOF
     # on at least one platform.
     inform "Building compiler"
     OBJECT_DIRECTORY=../objdir
-    contrib/gcc_build -d ${SOURCE_DIRECTORY} -o ${OBJECT_DIRECTORY} build || \
+    contrib/gcc_build -d ${SOURCE_DIRECTORY} -o ${OBJECT_DIRECTORY} \
+      -c "--enable-generated-files-in-srcdir" build || \
       error "Could not rebuild GCC"
-
-    # Regenerate the Fotran NEWS and BUGS files.
-    (cd ${OBJECT_DIRECTORY}/gcc && make f77.rebuilt) || \
-      error "Could not regenerate Fortran NEWS and BUGS files"
   fi
 
   # Move message catalogs to source directory.
   mv ../objdir/gcc/po/*.gmo gcc/po/
 
-  # Create a `.brik' file to use for checking the validity of the
-  # release.
-  changedir "${SOURCE_DIRECTORY}"
-  BRIK_FILE=`mktemp /tmp/gcc_release.XXXXXXX`
-  ((find . -type f | sort > $BRIK_FILE) && \
-       brik -Gb -f ${BRIK_FILE} > .brik && \
-       rm ${BRIK_FILE}) || \
-     error "Could not compute brik checksum"
+  # Create a "MD5SUMS" file to use for checking the validity of the release.
+  find . -type f |sed -e 's:^\./::' -e '/MD5SUMS/d' |sort |xargs md5sum >MD5SUMS
 }
 
 # Buid a single tarfile.  The first argument is the name of the name
@@ -231,11 +257,11 @@ EOF
 
 build_tarfile() {
   # Get the name of the destination tar file.
-  TARFILE="$1.tar.gz"
+  TARFILE="$1.tar.bz2"
   shift
 
   # Build the tar file itself.
-  (${TAR} cf - "$@" | ${GZIP} > ${TARFILE}) || \
+  (${TAR} cf - "$@" | ${BZIP2} > ${TARFILE}) || \
     error "Could not build tarfile"
   FILE_LIST="${FILE_LIST} ${TARFILE}"
 }
@@ -274,11 +300,11 @@ build_tarfiles() {
     `basename ${SOURCE_DIRECTORY}`
 }
 
-# Build .bz2 files.
-build_bzip2() {
+# Build .gz files.
+build_gzip() {
   for f in ${FILE_LIST}; do
-    bzfile=${f%.gz}.bz2
-    (zcat $f | ${BZIP2} > ${bzfile}) || error "Could not create ${bzfile}"
+    target=${f%.bz2}.gz
+    (${BZIP2} -d -c $f | ${GZIP} > ${target}) || error "Could not create ${target}"
   done
 }
 
@@ -286,19 +312,19 @@ build_bzip2() {
 build_diffs() {
   old_dir=${1%/*}
   old_file=${1##*/}
-  old_vers=${old_file%.tar.gz}
+  old_vers=${old_file%.tar.bz2}
   old_vers=${old_vers#gcc-}
   inform "Building diffs against version $old_vers"
   for f in gcc gcc-ada gcc-g++ gcc-g77 gcc-java gcc-objc gcc-testsuite gcc-core; do
-    old_tar=${old_dir}/${f}-${old_vers}.tar.gz
-    new_tar=${WORKING_DIRECTORY}/${f}-${RELEASE}.tar.gz
+    old_tar=${old_dir}/${f}-${old_vers}.tar.bz2
+    new_tar=${WORKING_DIRECTORY}/${f}-${RELEASE}.tar.bz2
     if [ ! -e $old_tar ]; then
       inform "$old_tar not found; not generating diff file"
     elif [ ! -e $new_tar ]; then
       inform "$new_tar not found; not generating diff file"
     else
       build_diff $old_tar gcc-${old_vers} $new_tar gcc-${RELEASE} \
-        ${f}-${old_vers}-${RELEASE}.diff.gz
+        ${f}-${old_vers}-${RELEASE}.diff.bz2
     fi
   done
 }
@@ -309,20 +335,19 @@ build_diff() {
   tmpdir=gccdiff.$$
   mkdir $tmpdir || error "Could not create directory $tmpdir"
   changedir $tmpdir
-  tar xfz $1 || error "Could not unpack $1 for diffs"
-  tar xfz $3 || error "Could not unpack $3 for diffs"
-  ${DIFF} $2 $4 > ../${5%.gz}
+  (${BZIP2} -d -c $1 | ${TAR} xf - ) || error "Could not unpack $1 for diffs"
+  (${BZIP2} -d -c $3 | ${TAR} xf - ) || error "Could not unpack $3 for diffs"
+  ${DIFF} $2 $4 > ../${5%.bz2}
   if [ $? -eq 2 ]; then
     error "Trouble making diffs from $1 to $3"
   fi
-  ${GZIP} ../${5%.gz} || error "Could not gzip ../${5%.gz}"
+  ${BZIP2} ../${5%.bz2} || error "Could not generate ../$5"
   changedir ..
   rm -rf $tmpdir
   FILE_LIST="${FILE_LIST} $5"
 }
 
 # Upload the files to the FTP server.
-
 upload_files() {
   inform "Uploading files"
 
@@ -356,6 +381,38 @@ upload_files() {
         || error "Could not upload ${x}"
     fi
   done
+}
+
+# Announce a snapshot, both on the web and via mail.
+announce_snapshot() {
+  inform "Updating links and READMEs on the FTP server"
+  
+  TEXT_DATE=`date --date=$DATE +%B\ %d,\ %Y`
+  changedir ~ftp/pub/gcc/snapshots
+  sed -e "s%@DATE@%$DATE%g" \
+    -e "s%@TEXT_DATE@%$TEXT_DATE%g" \
+    -e "s%@LAST_DATE@%$LAST_DATE%g" \
+    -e "s%@BRANCH@%${BRANCH}%g" \
+    -e "s%@RELEASE@%${RELEASE}%g" \
+    -e "s%@EXPORT@%${EXPORTTAG} ${EXPORTDATE}%g" \
+    ~/scripts/snapshot-README > $$
+  mv $$ ${RELEASE}/README
+  sed -e "s%@DATE@%$DATE%g" \
+    -e "s%@TEXT_DATE@%$TEXT_DATE%g" \
+    -e "s%@LAST_DATE@%$LAST_DATE%g" \
+    -e "s%@BRANCH@%${BRANCH}%g" \
+    -e "s%@RELEASE@%${RELEASE}%g" \
+    -e "s%@EXPORT@%${EXPORTTAG} ${EXPORTDATE}%g" \
+    ~/scripts/snapshot-index.html > $$
+  mv $$ ${RELEASE}/index.html
+
+  touch LATEST-IS-${BRANCH}-${DATE}
+  rm -f LATEST-IS-${BRANCH}-${LAST_DATE}
+
+  inform "Sending mail"
+
+  export QMAILHOST=gcc.gnu.org
+  mail -s "gcc-ss-${RELEASE} is now available" gcc@gcc.gnu.org < ~ftp/pub/gcc/snapshots/${RELEASE}/README
 }
 
 ########################################################################
@@ -394,8 +451,13 @@ RELEASE_REVISION=""
 # The complete name of the release.
 RELEASE=""
 
-# The name of the branch from which the release should be made.
+# The name of the branch from which the release should be made, in a 
+# user-friendly form.
 BRANCH=""
+
+# The name of the branch from which the release should be made, as used
+# for our version control system.
+CVSBRANCH=""
 
 # The tag to apply to the sources used for the release.
 TAG=""
@@ -432,13 +494,13 @@ SNAPSHOT=0
 LOCAL=0
 
 # Major operation modes.
-MODE_BZIP2=0
+MODE_GZIP=0
 MODE_DIFFS=0
 MODE_SOURCES=0
 MODE_TARFILES=0
 MODE_UPLOAD=0
 
-# .gz files generated to create .bz2 files from.
+# List of archive files generated; used to create .gz files from .bz2.
 FILE_LIST=""
 
 # Programs we use.
@@ -457,14 +519,17 @@ TAR="${TAR:-tar}"
 ########################################################################
 
 # Parse the options.
-while getopts "d:fr:u:t:p:sl" ARG; do
+while getopts "d:fr:u:t:p:s:l" ARG; do
     case $ARG in
     d)    DESTINATION="${OPTARG}";;
     r)    RELEASE="${OPTARG}";;
     t)    TAG="${OPTARG}";;
     u)    CVS_USERNAME="${OPTARG}";;
     f)    FINAL=1;;
-    s)    SNAPSHOT=1;;
+    s)    SNAPSHOT=1
+          BRANCH=${OPTARG%:*}
+          CVSBRANCH=${OPTARG#*:}
+          ;;
     l)    LOCAL=1
 	  SCP=cp
 	  FTP_PATH=~ftp/pub/gcc
@@ -477,6 +542,25 @@ while getopts "d:fr:u:t:p:sl" ARG; do
     esac
 done
 shift `expr ${OPTIND} - 1`
+
+# Handle the major modes.
+while [ $# -ne 0 ]; do
+    case $1 in
+    diffs)    MODE_DIFFS=1;;
+    gzip)     MODE_GZIP=1;;
+    sources)  MODE_SOURCES=1;;
+    tarfiles) MODE_TARFILES=1;;
+    upload)   MODE_UPLOAD=1;;
+    all)      MODE_SOURCES=1; MODE_TARFILES=1; MODE_DIFFS=1; MODE_UPLOAD=1;
+              if [ $SNAPSHOT -ne 1 ]; then
+                # Only for releases and pre-releases.
+                MODE_GZIP=1;
+              fi
+              ;;
+    *)        error "Unknown mode $1";;
+    esac
+    shift
+done
 
 # Perform consistency checking.
 if [ ${LOCAL} -eq 0 ] && [ -z ${CVS_USERNAME} ]; then
@@ -510,7 +594,7 @@ if [ $SNAPSHOT -eq 0 ]; then
 
   # Compute the name of the branch, which is based solely on the major
   # and minor release numbers.
-  BRANCH="gcc-${RELEASE_MAJOR}_${RELEASE_MINOR}-branch"
+  CVSBRANCH="gcc-${RELEASE_MAJOR}_${RELEASE_MINOR}-branch"
 
   # If this is not a final release, set various parameters acordingly.
   if [ ${FINAL} -ne 1 ]; then
@@ -520,19 +604,18 @@ if [ $SNAPSHOT -eq 0 ]; then
     FTP_PATH="${FTP_PATH}/releases/gcc-${RELEASE}/"
   fi
 else
-  RELEASE=$DATE
-  # For now snapshots come from the mainline.
-  BRANCH=HEAD
-  FTP_PATH="${FTP_PATH}/snapshots/${LONG_DATE}"
-  TAG=gcc_ss_${DATE}
+  RELEASE=${BRANCH}-${DATE}
+  FTP_PATH="${FTP_PATH}/snapshots/${RELEASE}"
+  if [ ${CVSBRANCH} != "HEAD" ]; then
+    TAG=gcc-ss-`echo ${RELEASE} | tr '.' '_'`
+  fi
 
   # Building locally on gcc.gnu.org, we know what the last snapshot date
   # was.
-  if [ $LOCAL -ne 0 ]; then
-    LAST_DATE=`cat ~/.snapshot_date`
-    LAST_LONG_DATE=`date --date=$LAST_DATE +%Y-%m-%d`
-    LAST_DIR=~ftp/pub/gcc/snapshots/${LAST_LONG_DATE}
-    OLD_TARS=${LAST_DIR}/gcc-${LAST_DATE}.tar.gz
+  if [ $MODE_DIFFS -ne 0 ] && [ $LOCAL -ne 0 ]; then
+    LAST_DATE=`cat ~/.snapshot_date-${BRANCH}`
+    LAST_DIR=~ftp/pub/gcc/snapshots/${BRANCH}-${LAST_DATE}
+    OLD_TARS=${LAST_DIR}/gcc-${BRANCH}-${LAST_DATE}.tar.bz2
   fi
 fi
 
@@ -566,25 +649,6 @@ export CVSROOT
 TZ="UTC0"
 export TZ
 
-# Handle the major modes.
-while [ $# -ne 0 ]; do
-    case $1 in
-    bzip2)    MODE_BZIP2=1;;
-    diffs)    MODE_DIFFS=1;;
-    sources)  MODE_SOURCES=1;;
-    tarfiles) MODE_TARFILES=1;;
-    upload)   MODE_UPLOAD=1;;
-    all)      MODE_SOURCES=1; MODE_TARFILES=1; MODE_DIFFS=1; MODE_UPLOAD=1;
-              if [ $SNAPSHOT -ne 1 ]; then
-                # Only for releases and pre-releases.
-                MODE_BZIP2=1;
-              fi
-              ;;
-    *)        error "Unknown mode $1";;
-    esac
-    shift
-done
-
 # Build the source directory.
 
 if [ $MODE_SOURCES -ne 0 ]; then
@@ -608,9 +672,9 @@ if [ $MODE_DIFFS -ne 0 ]; then
   fi
 fi
 
-# Build bzip2 files
-if [ $MODE_BZIP2 -ne 0 ]; then
-  build_bzip2
+# Build gzip files
+if [ $MODE_GZIP -ne 0 ]; then
+  build_gzip
 fi
 
 # Upload them to the FTP server.
@@ -620,28 +684,11 @@ if [ $MODE_UPLOAD -ne 0 ]; then
 
   # For snapshots, make some further updates.
   if [ $SNAPSHOT -ne 0 ] && [ $LOCAL -ne 0 ]; then
-    # Update links on the FTP server.
-    TEXT_DATE=`date --date=$DATE +%B\ %d,\ %Y`
-    cd ~ftp/pub/gcc/snapshots
-    sed -e "s%@DATE@%$DATE%g" -e "s%@LAST_DATE@%$LAST_DATE%g" \
-      -e "s%@LONG_DATE@%$LONG_DATE%g" \
-      -e "s%@TEXT_DATE@%$TEXT_DATE%g" < ~/scripts/snapshot-README > $$
-    mv $$ README
-    sed -e "s%@DATE@%$DATE%g" -e "s%@LAST_DATE@%$LAST_DATE%g" \
-      -e "s%@LONG_DATE@%$LONG_DATE%g" \
-      -e "s%@TEXT_DATE@%$TEXT_DATE%g" < ~/scripts/snapshot-index.html > $$
-    mv $$ index.html
-
-    touch LATEST-IS-$LONG_DATE
-    rm -f LATEST-IS-$LAST_LONG_DATE
+    announce_snapshot
 
     # Update snapshot date file.
     changedir ~
-    echo $DATE >.snapshot_date
-
-    # Announce the snapshot.
-    export QMAILHOST=gcc.gnu.org
-    mail -s "gcc-ss-$DATE is now available" gcc@gcc.gnu.org < ~ftp/pub/gcc/snapshots/README
+    echo $DATE > .snapshot_date-${BRANCH}
 
     # Remove working directory
     rm -rf ${WORKING_DIRECTORY}
