Import tetex 2.0.1.
git-svn-id: svn+ssh://svn.mit.edu/athena/branches/vendor@18907 728af825-273c-0410-89f9-f7d3b574a069

diff --git a/third/tetex/src/texk/kpathsea/mktexpk b/third/tetex/src/texk/kpathsea/mktexpk
--- a/third/tetex/src/texk/kpathsea/mktexpk
+++ b/third/tetex/src/texk/kpathsea/mktexpk
@@ -4,10 +4,10 @@
 # (If you change or delete the word `original' on the previous line,
 # installation won't write this script over yours.)
 # 
-# te@informatik.uni-hannover.de, kb@mail.tug.org, and infovore@xs4all.nl.
+# te@dbs.uni-hannover.de, kb@mail.tug.org, and infovore@xs4all.nl.
 # Public domain.
 
-version='$Id: mktexpk,v 1.1.1.1 2000-03-10 17:51:27 ghudson Exp $'
+version='$Id: mktexpk,v 1.1.1.2 2003-02-25 22:11:57 amb Exp $'
 progname=`echo $0 | sed 's%.*/%%'`
 usage="Usage: $progname [OPTIONS] NAME [REDIRECT],
   Create a PK font.
@@ -86,65 +86,19 @@ esac
 
 NAME=$1
 
-# ps_to_pk is set in mktex.opt
-case $ps_to_pk in
-  gsftopk)
-    if $ps_to_pk -t "$NAME"; then
-      cmd="$ps_to_pk $NAME $DPI"
-    fi;;
-  ps2pk)
-    # grep for the font in $PSMAPFILE.  These are base font names, such as
-    # rpplr (the original) or pplr0 (an interim step) or pplr8r (current).
-    : ${PSMAPFILE=`kpsewhich --format='dvips config' ps2pk.map psfonts.map`}
-    pattern="^$NAME"'([ 	]|$)' 
-    psline=`egrep "$pattern" $PSMAPFILE`
-    if test -n "$psline"; then
-      set x `echo "$psline" | sed 's%[<["]%%g'`
-      shift; shift; shift;
-      encoding=; psname=; slant=; extend=
-      while test ! -z "$1"; do
-        case "$1" in
-          *.enc)       encoding="-e $1";;
-          *.pf[ab])    psname="$1";;
-          *SlantFont)  slant="-S $lastopt";;
-          *ExtendFont) extend="-E $lastopt";;
-        esac
-        lastopt="$1"
-        shift
-      done
-      # Guessing the name of the type1 font file as fallback:
-      ANAME=`echo $NAME | sed 's/8r$/8a/'`
-      for i in $NAME.pfa $NAME.pfb $ANAME.pfa $ANAME.pfb; do
-        if kpsewhich $i >/dev/null 2>&1; then
-          psname=$i
-          break
-        fi
-      done
-      if [ -z "$psname" ]; then
-        echo "$progname: cannot find $NAME.pfa or $NAME.pfb. Trying gsftopk." >&2
-        cmd="gsftopk $NAME $DPI"
-      else
-        cmd="ps2pk -v -X$DPI -R$BDPI $slant $extend $encoding $psname $NAME.${DPI}pk"
-      fi
-    fi;;
-esac
-
-if test -z "$cmd"; then
-  if (ttf2pk -t -q $NAME) >/dev/null 2>&1; then
-    cmd="ttf2pk -q $NAME $DPI"
-  elif (hbf2gf -t -q $NAME) >/dev/null 2>&1; then
-    cmd="hbf2gf -q -p $NAME $DPI"
+if kpsewhich $NAME.mf >/dev/null 2>&1 || mktexmf $NAME >/dev/null 2>&1; then
+  # determine the progname of metafont to use; prefer mf-nowin.
+  if (mf-nowin --version) >/dev/null 2>&1; then
+    MF="mf-nowin -progname=mf"
+  else
+    MF=mf
   fi
-fi
 
-if test -n "$cmd"; then
-  MODE=modeless
-else
   # Check that $BDPI and $MODE are consistent; if not, ignore the mode and
   # hope we can correctly guess it from bdpi.  (People like to specify the
   # resolution on the command line, not the mode so much.)
   if test -n "$MODE"; then
-    mf_bdpi=`mf \
+    mf_bdpi=`$MF \
 '\mode:='$MODE';mode_setup;message"BDPI= "&decimal round pixels_per_inch;end.'\
              </dev/null \
              | awk '/DPI=/ {print $2}'`
@@ -173,7 +127,66 @@ else
 
   # Run Metafont. Always use plain Metafont, since reading cmbase.mf
   # does not noticeably slow things down.
-  cmd="mf \mode:=$MODE; mag:=$MAG; nonstopmode; input $NAME"
+  cmd="$MF \mode:=$MODE; mag:=$MAG; nonstopmode; input $NAME"
+else
+  MODE=modeless
+  # ps_to_pk is set in mktex.opt
+  case $ps_to_pk in
+    gsftopk)
+      if $ps_to_pk -t "$NAME"; then
+        cmd="$ps_to_pk $NAME $DPI"
+      fi;;
+    ps2pk)
+      # grep for the font in $PSMAPFILE.  These are base font names, such as
+      # rpplr (the original) or pplr0 (an interim step) or pplr8r (current).
+      : ${PSMAPFILE=`kpsewhich --format='dvips config' psfonts.map ps2pk.map`}
+      pattern="^$NAME"'([ 	]|$)' 
+      psline=`egrep "$pattern" $PSMAPFILE | tail -1`
+      if test -n "$psline"; then
+        set x `echo "$psline" | sed 's%[<["]%%g'`
+        shift; shift; shift;
+        encoding=; psname=; slant=; extend=
+        while test ! -z "$1"; do
+          case "$1" in
+            *.enc)       encoding="-e $1";;
+            *.pf[ab])    psname="$1";;
+            *SlantFont)  slant="-S $lastopt";;
+            *ExtendFont) extend="-E $lastopt";;
+          esac
+          lastopt="$1"
+          shift
+        done
+        # Guessing the name of the type1 font file as fallback:
+        ANAME=`echo $NAME | sed 's/8r$/8a/'`
+        for i in $NAME.pfa $NAME.pfb $ANAME.pfa $ANAME.pfb; do
+          if kpsewhich $i >/dev/null 2>&1; then
+            psname=$i
+            break
+          fi
+        done
+
+        if [ -n "$psname" ]; then
+          cmd="ps2pk -v -X$DPI -R$BDPI $slant $extend $encoding $psname $NAME.${DPI}pk"
+        else
+          if gsftopk -t "$NAME"; then
+            echo "$progname: cannot find $NAME.pfa or $NAME.pfb. Trying gsftopk." >&2
+            cmd="gsftopk $NAME $DPI"
+          fi
+        fi
+      fi;;
+  esac
+
+  # unsupported by $ps_to_pk, try other conversions:
+  if test -z "$cmd"; then
+    if (ttf2pk -t -q $NAME) >/dev/null 2>&1; then
+      cmd="ttf2pk -q $NAME $DPI"
+    elif (hbf2gf -t -q $NAME) >/dev/null 2>&1; then
+      cmd="hbf2gf -q -p $NAME $DPI"
+    else
+      echo "$progname: don't know how to create bitmap font for $NAME." >&2
+      exit 1
+    fi
+  fi
 fi
 
 OIFS=$IFS; IFS=$SEP
diff --git a/third/tetex/src/texk/tetex/fmtutil b/third/tetex/src/texk/tetex/fmtutil
--- a/third/tetex/src/texk/tetex/fmtutil
+++ b/third/tetex/src/texk/tetex/fmtutil
@@ -3,7 +3,7 @@
 ###############################################################################
 # fmtutil: utility to maintain format files.
 #
-# Thomas Esser, (C) 1998. Public domain.
+# Thomas Esser, (C) 1998, 2001, 2002, 2003. Public domain.
 #
 # Commands:
 #  --all                      recreate all format files
@@ -18,7 +18,25 @@
 #  --fmtdir directory         set destination directory for format files
 ###############################################################################
 
+###############################################################################
+# program history:
+#   Sat Feb 15 22:01:35 CET 2003   let mf-nowin work without mf
+#   Wed Dec 25 09:47:44 CET 2002   bugfix for localized pool files
+#   Fri Oct 25 02:29:06 CEST 2002: now more careful about find_hyphenfile()
+#   Tue Oct 22 22:46:48 CEST 2002: -jobname, oft extension
+#   Fri Oct  4 22:33:17 CEST 2002: add more cli stuff: enablefmt
+#                                  disablefmt listcfg
+#   Sun Jul  7 21:28:37 CEST 2002: look at log file for possible problems,
+#                                  and issue a warning
+#   Tue Jun  4 21:52:57 CEST 2002: trap / cleanup code from updmap
+#   Tue Jun  4 19:32:44 CEST 2002: be smarter about stdout / stderr
+#   Tue Apr  9 22:46:34 CEST 2002: pass -progname=mpost for metafun
+#   Tue Apr  2 00:37:39 CEST 2002: added mktexfmt functionality
+#   Tue Jun  5 14:45:57 CEST 2001: added support for mf / mpost
+###############################################################################
+
 progname=fmtutil
+version=2.0
 
 test -f /bin/sh5 && test -z "$RUNNING_SH5" \
   && { UNAMES=`uname -s`; test "x$UNAMES" = xULTRIX; } 2>/dev/null \
@@ -30,7 +48,59 @@ test -f /bin/bsh && test -z "$RUNNING_BSH" \
   && { RUNNING_BSH=true; export RUNNING_BSH; exec /bin/bsh $0 ${1+"$@"}; }
 unset RUNNING_BSH
 
+# hack around a bug in zsh:
+test -n "${ZSH_VERSION+set}" && alias -g '${1+"$@"}'='"$@"'
+
 cnf=fmtutil.cnf   # name of the config file
+
+###############################################################################
+# cleanup()
+#   clean up the temp area and exit with proper exit status
+###############################################################################
+cleanup()
+{
+  rc=$?
+  $needsCleanup && test -n "$tmpdir" && test -d "$tmpdir" \
+    && { rm -f "$tmpdir"/*; cd /; rmdir "$tmpdir"; }
+  exit $rc
+}
+
+###############################################################################
+# setupTmpDir()
+#   set up a temp directory and a trap to remove it
+###############################################################################
+setupTmpDir()
+{
+  $needsCleanup && return
+
+  trap 'cleanup' 1 2 3 7 13 15
+  needsCleanup=true
+  (umask 077; mkdir "$tmpdir") \
+    || abort "could not create directory \`$tmpdir'"
+}
+
+###############################################################################
+# configReplace(file, pattern, line)
+#   The first line in file that matches pattern gets replaced by line.
+#   line will be added at the end of the file if pattern does not match.
+###############################################################################
+configReplace()
+{
+  file=$1; pat=$2; line=$3
+
+  if grep "$pat" "$file" >/dev/null; then
+    ed "$file" >/dev/null 2>&1 <<-eof
+	/$pat/
+	c
+	$line
+	.
+	w
+	q
+eof
+  else
+    echo "$line" >> $file
+  fi
+}
 
 ###############################################################################
 # setmatch(match)
@@ -59,7 +129,7 @@ getmatch()
 cache_vars()
 {
   : ${MT_VARTEXFONTS=`kpsewhich --expand-var='$VARTEXFONTS' | sed 's%^!!%%'`}
-  : ${MT_TEXMFMAIN=`kpsewhich --expand-path='$TEXMFMAIN'`}
+  : ${MT_TEXMFMAIN=`kpsewhich --expand-var='$TEXMFMAIN'`}
   : ${MT_MKTEXNAM=`kpsewhich --format='web2c files' mktexnam`}
   : ${MT_MKTEXNAM_OPT=`kpsewhich --format='web2c files' mktexnam.opt`}
   : ${MT_MKTEXDIR=`kpsewhich --format='web2c files' mktexdir`}
@@ -94,11 +164,15 @@ Valid commands:
   --missing                  create all missing format files
   --byfmt formatname         (re)create format for `formatname'
   --byhyphen hyphenfile      (re)create formats that depend on `hyphenfile'
+  --enablefmt formatname     enable formatname in config file
+  --disablefmt formatname    disable formatname in config file
+  --listcfg                  list (enabled and disabled) configurations
   --showhyphen formatname    print name of hyphenfile for format `formatname'
   --edit                     edit fmtutil.cnf file
   --help                     show this message
 eof
-  exit
+  true
+  cleanup
 }
 
 ###############################################################################
@@ -108,7 +182,74 @@ eof
 abort()
 {
   echo "$progname: $1." >&2
-  exit 1
+  false  # some systems need this to set nonzero $?
+  cleanup
+}
+
+###############################################################################
+# byebye()
+#   report any failures and exit the program
+###############################################################################
+byebye()
+{
+  if $has_errors; then
+    {
+      cat <<eof
+
+###############################################################################
+$progname: Error! Not all formats have been built successfully.
+Visit the log files in directory
+  $destdir
+for details.
+###############################################################################
+
+This is a summary of all \`failed' messages and warnings:
+$log_failure_msg
+eof
+    } >&2
+    false  # some systems need this to set nonzero $?
+    cleanup
+  else
+    true
+    cleanup
+  fi
+}
+
+###############################################################################
+# init_log_failure()
+#   reset the list of failure messages
+###############################################################################
+init_log_failure()
+{
+  log_failure_msg=
+  has_errors=false
+}
+
+###############################################################################
+# log_failure(errmsg)
+#   report and save failure message `errmsg'
+###############################################################################
+log_failure()
+{
+  echo "Error: $@" >&2
+  if test -z "$log_failure_msg"; then
+    log_failure_msg="$@"
+  else
+    OLDIFS=$IFS; IFS=
+    log_failure_msg="$log_failure_msg
+$@"
+    IFS=$OLDIFS
+  fi
+  has_errors=true
+}
+
+###############################################################################
+# verbose (cmd)
+#   execute cmd. Redirect output depending on $mktexfmtMode.
+###############################################################################
+verbose()
+{
+  $mktexfmtMode && ${1+"$@"} >&2 || ${1+"$@"}
 }
 
 ###############################################################################
@@ -121,6 +262,26 @@ main()
   destdir=     # global variable: where do we put the format files?
   cnf_file=    # global variable: full name of the config file
   cmd=         # desired action from command line
+  needsCleanup=false
+  need_find_hyphenfile=false
+
+  # mktexfmtMode: if called as mktexfmt, set to true. Will echo the generated
+  # filename after successful generation to stdout then (and nothing else).
+  mktexfmtMode=false
+  case $0 in
+    mktexfmt|*/mktexfmt)
+      mktexfmtMode=true
+      fullfmt=$1; shift
+      case $fullfmt in
+        *.oft|*.fmt|*.efmt|*.mem|*.base)
+           set x --byfmt `echo $fullfmt | sed 's@\.[a-z]*$@@'` ${1+"$@"}; shift
+           ;;
+        *) abort "unknown format type: $fullfmt"
+           ;;
+      esac
+      ;;
+  esac
+
   while
     case $1 in
       --cnffile)
@@ -151,6 +312,16 @@ main()
           cmd=showhyphen; arg=`echo "$1" | sed 's/--showhyphen=//'`; shift ;;
       --help|-help)
           cmd=help;;
+      --enablefmt)
+          shift; cmd=enablefmt; arg=$1;;
+      --enablefmt=*)
+          cmd=enablefmt; arg=`echo "$1" | sed 's/--enablefmt=//'`; shift ;;
+      --disablefmt)
+          shift; cmd=disablefmt; arg=$1;;
+      --disablefmt=*)
+          cmd=disablefmt; arg=`echo "$1" | sed 's/--disablefmt=//'`; shift ;;
+      --listcfg)
+          cmd=listcfg;;
       --quiet|--test|--dolinks|--force)
           ;;
       "") break;;
@@ -171,10 +342,20 @@ main()
   case "$cmd" in
     showhyphen)
       show_hyphen_file "$arg"
-      exit $?;;
+      cleanup
+      ;;
     edit)
       ${VISUAL-${EDITOR-vi}} $cnf_file
-      exit;;
+      cleanup
+      ;;
+    enablefmt|disablefmt)
+      $cmd $arg
+      cleanup
+      ;;
+    listcfg)
+      listcfg
+      cleanup
+      ;;
   esac
 
   # set up destdir:
@@ -184,20 +365,22 @@ main()
     test -z "$VARTEXMF" && VARTEXMF=$MT_TEXMFMAIN
     destdir=$VARTEXMF/web2c
   fi
+  test -d "$destdir" || $MT_MKTEXDIR "$destdir" >/dev/null 2>&1
   test -d "$destdir" || abort "format directory \`$destdir' does not exist"
 
   # find mktexupd script:
   test -n "$MT_MKTEXUPD" || MT_MKTEXUPD="$TEXMFMAIN/web2c/mktexupd"
 
-  thisdir=`pwd 2>/dev/null`
-  if test -n "$thisdir"; then
-    : ${KPSE_DOT=$thisdir}
-    TEXINPUTS="$thisdir:$TEXINPUTS"
-  fi
+  thisdir=`pwd`
+  : ${KPSE_DOT=$thisdir}
+  export KPSE_DOT
+
   tmpdir=${TMP-/tmp}/$progname.$$
-  trap 'cd /; cd "$thisdir"; rm -rf "$tmpdir"; exit 0' 0 1 2 3 7 13 15
-  mkdir "$tmpdir" || abort "could not create directory \`$tmpdir'"
-  cd "$tmpdir" || exit 1
+  setupTmpDir
+  cd "$tmpdir" || {
+    false  # some systems need this to set nonzero $?
+    cleanup
+  }
 
   # make local paths absolute:
   case "$destdir" in
@@ -209,7 +392,7 @@ main()
     *)  cnf_file="$thisdir/$cnf_file";;
   esac
 
-
+  init_log_failure
   # execute the desired command:
   case "$cmd" in 
     all)
@@ -228,13 +411,17 @@ main()
     rm -f "$destdir/$i"
     mv "$i" "$destdir/$i"
   done
-  for i in *fmt; do
+  for i in *.oft *.fmt *.efmt *.mem *.base; do
     test -f "$i" || continue
     rm -f "$destdir/$i"
-    mv "$i" "$destdir/$i" \
-      && echo "$progname: $destdir/$i successfully generated." >&2
+    if mv "$i" "$destdir/$i"; then
+      verbose echo "$progname: $destdir/$i installed."
+      $mktexfmtMode && echo "$destdir/$i"
+    fi
     $MT_MKTEXUPD "$destdir" "$i"
   done
+
+  # symlinks for "plain" (tex/etex/mf/mpost)
   if test -f "$destdir/tex.fmt" && test ! -f "$destdir/plain.fmt"; then
     ln -s tex.fmt "$destdir/plain.fmt"
     $MT_MKTEXUPD "$destdir" plain.fmt
@@ -243,6 +430,23 @@ main()
     ln -s tex.efmt "$destdir/plain.efmt"
     $MT_MKTEXUPD "$destdir" plain.efmt
   fi
+  if test -f "$destdir/mf.base" && test ! -f "$destdir/plain.base"; then
+    ln -s mf.base "$destdir/plain.base"
+    $MT_MKTEXUPD "$destdir" mf.base
+  fi
+  if test -f "$destdir/mf.base" && test ! -f "$destdir/mf-nowin.base"; then
+    ln -s mf.base "$destdir/mf-nowin.base"
+    $MT_MKTEXUPD "$destdir" mf-nowin.base
+  fi
+  if test -f "$destdir/mf.base" && test ! -f "$destdir/mfw.base"; then
+    ln -s mf.base "$destdir/mfw.base"
+    $MT_MKTEXUPD "$destdir" mfw.base
+  fi
+  if test -f "$destdir/mpost.mem" && test ! -f "$destdir/plain.mem"; then
+    ln -s mpost.mem "$destdir/plain.mem"
+    $MT_MKTEXUPD "$destdir" plain.mem
+  fi
+  byebye
 }
 
 ###############################################################################
@@ -252,6 +456,16 @@ main()
 #   texargs: flags for initex and name of the ini file (e.g. -mltex frlatex.ini)
 #   fmtfile: name of the format file (without directory, but with extension)
 #
+#   Support for building internationalized formats sets:
+#     pool: base name of pool file (to support translated pool files)
+#     tcx: translation file used when creating the format
+#
+#   Example (for fmtutil.cnf):
+#     mex-pl tex mexconf.tex nls=tex-pl,il2-pl mex.ini
+#
+#   The nls parameter (pool,tcx) can only be specified as the first argument
+#   inside the 4th field in fmtutil.cnf.
+#
 # exit code: returns error code if the ini file is not installed
 ###############################################################################
 parse_line()
@@ -260,18 +474,33 @@ parse_line()
   engine=$2
   hyphenation=$3
   shift; shift; shift
+
+  # handle nls support: pool + tcx
+  pool=; tcx=
+  case $1 in
+    nls=*)
+      pool=`echo $1 | sed 's@nls=@@; s@,.*@@'`
+      tcx=`echo $1 | sed 's@nls=[^,]*@@; s@^,@@'`
+      shift      # nls stuff is not handled by the engine directly,
+                 # so we shift this away
+      ;;
+  esac
+
   texargs="$@"
 
   eval lastarg=\$$#
   inifile=`echo $lastarg | sed 's%^\*%%'`
 
   case "$engine" in
-    *etex) fmtfile="$format.efmt";;
-    *)     fmtfile="$format.fmt";;
+    *etex)  fmtfile="$format.efmt"; kpsefmt=tex;;
+    omega)  fmtfile="$format.oft";  kpsefmt=tex;;
+    mpost)  fmtfile="$format.mem";  kpsefmt=mpost;;
+    mf|mfw|mf-nowin) fmtfile="$format.base"; kpsefmt=mf;;
+    *)      fmtfile="$format.fmt";  kpsefmt=tex;;
   esac
 
   # See if we can find $inifile for return code:
-  kpsewhich -progname=$format -format=tex $inifile >/dev/null 2>&1
+  kpsewhich -progname=$format -format=$kpsefmt $inifile >/dev/null 2>&1
 }
 
 ###############################################################################
@@ -282,7 +511,10 @@ parse_line()
 find_hyphenfile()
 {
   format="$1"; hyphenation="$2"
-  kpsewhich -progname="$format" -format=tex "$hyphenation"
+  case $hyphenation in
+    -) ;;
+    *) kpsewhich -progname="$format" -format=tex "$hyphenation";;
+  esac
 }
 
 ###############################################################################
@@ -305,23 +537,45 @@ find_info_for_name()
 ###############################################################################
 run_initex()
 {
-  # use -efmt=xxx for e-TeX and -fmt=xxx for other engines:
-  case "$engine" in
-    *etex) fmtswitch="-efmt=$format";;
-    *)     fmtswitch="-fmt=$format";;
-  esac
 
+  # install a pool file and set tcx flag if requested in lang= option:
+  rm -f *.pool
+  poolfile=
+  tcxflag=
+  test -n "$pool" \
+    && poolfile=`(kpsewhich -progname=$engine $pool.pool) 2>/dev/null`
+  if test -n "$poolfile" && test -f "$poolfile"; then
+    verbose echo "$progname: attempting to create localized format using pool=$pool and tcx=$tcx."
+    cp "$poolfile" $engine.pool
+    test -n "$tcx" && tcxflag=-translate-file=$tcx
+    localpool=true
+  else
+    localpool=false
+  fi
+
+  jobswitch="-jobname=$format"
   case "$format" in
+    metafun) prgswitch=-progname=mpost;;
     cont-??) prgswitch=-progname=context;;
     *)       prgswitch=-progname=$format;;
   esac
 
   rm -f $fmtfile
-  $engine -ini $fmtswitch $prgswitch $texargs </dev/null
-  test -f $fmtfile || {
-    abort "\`$engine -ini $fmtswitch $prgswitch $texargs' failed"
-    rm -f $fmtfile
-  }
+  verbose echo "running \`$engine -ini  $tcxflag $jobswitch $prgswitch $texargs' ..."
+
+  # run in a subshell to get a local effect of TEXPOOL manipulation:
+  (
+    # If necessary, set TEXPOOL. Use absolute path, because of KPSE_DOT.
+    $localpool && { TEXPOOL="`pwd`:$TEXPOOL"; export TEXPOOL; }
+    verbose $engine -ini $tcxflag $jobswitch $prgswitch $texargs
+  ) </dev/null
+
+  if test -f $fmtfile; then
+    grep '^! ' $format.log >/dev/null 2>&1 &&
+      log_failure "\`$engine -ini $tcxflag $jobswitch $prgswitch $texargs' possibly failed."
+  else
+    log_failure "\`$engine -ini $tcxflag $jobswitch $prgswitch $texargs' failed"
+  fi
 }
 
 ###############################################################################
@@ -336,7 +590,8 @@ recreate_loop()
 '
   set `echo x; sed '/^#/d; /^[ 	]*$/d' "$cnf_file"`; shift
   IFS=$OIFS
-  for line in "$@"; do
+  for line
+  do
     parse_line $line || continue
     check_match || continue
     echo; echo
@@ -350,7 +605,9 @@ recreate_loop()
 ###############################################################################
 check_match()
 {
-  this_hyphenfile=`find_hyphenfile "$format" "$hyphenation"`
+  $need_find_hyphenfile && \
+    this_hyphenfile=`find_hyphenfile "$format" "$hyphenation"`
+
   eval $match_cmd && setmatch true
 }
 
@@ -372,7 +629,8 @@ create_one_format()
 ###############################################################################
 create_missing()
 {
-  match_cmd='test ! -f $destdir/$fmtfile'
+  # match_cmd='test ! -f $destdir/$fmtfile'
+  match_cmd='test ! -f "`kpsewhich -progname=$format $fmtfile`"'
   recreate_loop
 }
 
@@ -394,6 +652,7 @@ recreate_by_hyphenfile()
 {
   hyphenfile=$1
 
+  need_find_hyphenfile=true
   match_cmd="test x\$this_hyphenfile = x$hyphenfile"
 
   # No match before the loop:
@@ -420,9 +679,52 @@ show_hyphen_file()
   find_info_for_name "$fmtname" || abort "no info for format \`$fmtname'"
   if test "x$hyphenation" = x-; then
     echo -
-    exit 0
+    cleanup
   fi
-  find_hyphenfile "$format" "$hyphenation" || abort "hyphenfile \`$hyphenation' not found"
+  find_hyphenfile "$format" "$hyphenation" \
+    || abort "hyphenfile \`$hyphenation' not found"
 }
 
-main "$@"
+###############################################################################
+# listcfg()
+#   prints all format definitions in config files (enabled and disabled ones)
+###############################################################################
+listcfg()
+{
+  egrep '^(#! *)?[a-zA-Z]' $cnf_file
+}
+
+###############################################################################
+# disablefmt(format)
+#   disables format in configuration file
+###############################################################################
+disablefmt()
+{
+  grep "^$1	" $cnf_file >/dev/null || return 0
+
+  ed $cnf_file >/dev/null 2>&1 <<-eof
+	/^$1	/s/^/#! /
+	w
+	q
+eof
+  return 0
+}
+
+###############################################################################
+#  enablefmt(format)
+#    enables format in configuration file
+###############################################################################
+enablefmt()
+{
+  grep "^#! *$1	" $cnf_file >/dev/null || return 0
+  ed $cnf_file >/dev/null 2>&1 <<-eof
+	/^#! *$1	/s/.. *//
+	w
+	q
+eof
+  return 0
+}
+
+main ${1+"$@"}
+true
+cleanup
diff --git a/third/tetex/src/texk/tetex/texlinks b/third/tetex/src/texk/tetex/texlinks
--- a/third/tetex/src/texk/tetex/texlinks
+++ b/third/tetex/src/texk/tetex/texlinks
@@ -1,11 +1,13 @@
 #!/bin/sh
 
-# Copyright Thomas Esser, 1999. public domain.
+# Copyright Thomas Esser, 1999, 2002. public domain.
 
 # texlinks: script to maintain symlinks from format to engine. Interprets
 # the lines given in fmtutil.cnf.
 
-# TODO: add a --help option
+# History:
+#   Tue Apr  9 22:46:34 CEST 2002, te:
+#       do not create symlinks for cont-??, metafun and mptopdf
 
 test -f /bin/sh5 && test -z "$RUNNING_SH5" \
   && { UNAMES=`uname -s`; test "x$UNAMES" = xULTRIX; } 2>/dev/null \
@@ -16,6 +18,9 @@ test -f /bin/bsh && test -z "$RUNNING_BSH" \
   && { UNAMES=`uname -s`; test "x$UNAMES" = xAIX; } 2>/dev/null \
   && { RUNNING_BSH=true; export RUNNING_BSH; exec /bin/bsh $0 ${1+"$@"}; }
 unset RUNNING_BSH
+
+# hack around a bug in zsh:
+test -n "${ZSH_VERSION+set}" && alias -g '${1+"$@"}'='"$@"'
 
 cnf=fmtutil.cnf   # name of the config file
 usage='texlinks [options] [directories]
@@ -45,7 +50,7 @@ If no directories are specified the list of directories depends on the
 # abort(errmsg)
 #   print `errmsg' to stderr and exit with error code 1
 ###############################################################################
-abort() { errmsg "texlinks: $1."; exit 1; }
+abort() { errmsg "texlinks: $1."; false; cleanup; }
 
 # error message to stderr:
 errmsg() { echo "$@" >&2; }
@@ -55,6 +60,33 @@ verbose_echo() { $verbose && errmsg "$@"; }
 
 # in verbose mode: show command that is executed:
 verbose_do() { verbose_echo "$@"; "$@"; }
+
+###############################################################################
+# cleanup()
+#   clean up the temp area and exit with proper exit status
+###############################################################################
+cleanup()
+{
+  rc=$?
+  $needsCleanup && test -n "$tmpdir" && test -d "$tmpdir" \
+    && { rm -f "$tmpdir"/*; cd /; rmdir "$tmpdir"; }
+  exit $rc
+}
+
+###############################################################################
+# setupTmpDir()
+#   set up a temp directory and a trap to remove it
+###############################################################################
+setupTmpDir()
+{
+  $needsCleanup && return
+
+  trap 'cleanup' 1 2 3 7 13 15
+  needsCleanup=true
+  (umask 077; mkdir "$tmpdir") \
+    || abort "could not create directory \`$tmpdir'"
+}
+
 
 # search a binary along $PATH:
 check_for_binary()
@@ -82,20 +114,61 @@ install_link()
   # make symlink    src -> dest
   dest=$1; src=$2
 
-  test "x$src" != "x`(ls -ld $src | awk '{print $NF}') 2>/dev/null`" &&
-    verbose_do rm -f "$src";
+  case $src in
+    */mf)
+      if test $dest = "mf-nowin" && test -f $selfautoloc/mfw; then
+        dest="mfw"
+        verbose_echo "both mfw and mf-nowin exists, $src linked to $dest"
+      fi
+      ;;
+  esac
+
+  case $src in
+    */cont-??|*/metafun|*/mptopdf)
+      verbose_echo "symlink $2 -> $dest skipped (special case)"
+      ;;
+    */csplain|*/cslatex|*/pdfcslatex|*/pdfcsplain)
+      verbose_do rm -f "$src"
+      cat > $src <<'eof'
+#!/bin/sh
+
+test -f /bin/sh5 && test -z "$RUNNING_SH5" \
+  && { UNAMES=`uname -s`; test "x$UNAMES" = xULTRIX; } 2>/dev/null \
+  && { RUNNING_SH5=true; export RUNNING_SH5; exec /bin/sh5 $0 ${1+"$@"}; }
+unset RUNNING_SH5
+
+test -f /bin/bsh && test -z "$RUNNING_BSH" \
+  && { UNAMES=`uname -s`; test "x$UNAMES" = xAIX; } 2>/dev/null \
+  && { RUNNING_BSH=true; export RUNNING_BSH; exec /bin/bsh $0 ${1+"$@"}; }
+unset RUNNING_BSH
+
+# hack around a bug in zsh:
+test -n "${ZSH_VERSION+set}" && alias -g '${1+"$@"}'='"$@"'
+
+eof
+      cat >> $src <<eof
+$dest -progname=`basename $src` -default-translate-file=il2-cs \${1+"\$@"}
+eof
+      chmod 755 $src
+      verbose_echo "wrapper file $src created."
+      ;;
+    *)
+      test "x$src" != "x`(ls -ld $src | awk '{print $NF}') 2>/dev/null`" &&
+        verbose_do rm -f "$src"
   
-  if test -f "$src"; then
-    case $silent in
-      true)
-        ;;
-      *)
-        errmsg "install_link failed for $src. File already exists."
-        ;;
-    esac
-  else
-    verbose_do ln -s "$dest" "$src"
-  fi
+      if test -f "$src"; then
+        case $silent in
+          true)
+            ;;
+          *)
+            errmsg "install_link failed for $src. File already exists."
+            ;;
+        esac
+      else
+        verbose_do ln -s "$dest" "$src"
+      fi
+      ;;
+   esac
 }
 
 ###############################################################################
@@ -126,7 +199,7 @@ search_symlinkdir()
 ###############################################################################
 upd_symlinkdir()
 {
-  search_symlinkdir || return
+  search_symlinkdir || return 0
   for i in `sed 's@ .*@@' cnf_file_ln.$$`; do
     install_link "$selfautoloc/$i" "$symlinkdir/$i"
   done
@@ -141,6 +214,8 @@ main()
 {
   cnf_file=    # global variable: full name of the config file
   dirs=
+  needsCleanup=false
+
   multiplatform=false
   verbose=false
   silent=false
@@ -150,7 +225,7 @@ main()
   while 
     case $1 in
       --h*|-h)
-          echo "$usage"; exit;;
+          echo "$usage"; exit 0;;
       --cnffile|-f)
           shift; cnf_file=$1;;
       --v*|-v) verbose=true;;
@@ -166,10 +241,13 @@ main()
   test -z "$cnf_file" && cnf_file=`kpsewhich --format='web2c files' $cnf`
   test -f "$cnf_file" || abort "config file \`$cnf' not found"
 
-  tmpdir=${TMP-/tmp}/fmtutil.$$
-  trap 'cd /; cd "$thisdir"; rm -rf "$tmpdir"; exit 0' 0 1 2 3 7 13 15
-  mkdir "$tmpdir" || abort "could not create directory \`$tmpdir'"
-  cd "$tmpdir" || exit 1
+
+  tmpdir=${TMP-/tmp}/texlinks.$$
+  setupTmpDir
+  cd "$tmpdir" || {
+    false  # some systems need this to set nonzero $?
+    cleanup
+  }
 
   sed '/^[ 	]*#/d; /^[ 	]*$/d' $cnf_file \
     | awk '{print $1, $2}' > cnf_file_ln.$$
@@ -215,4 +293,8 @@ main()
   upd_symlinkdir
 }
 
-main "$@"
+main ${1+"$@"}
+
+# set successful return code
+true
+cleanup
