- Pick a (slightly) less silly stamps directory (Trac: #727)  - Ensure that we don't accidentally end up with parallel builds because of    stray .started or .error stamps (Trac: #1230)  - Suppress echoing of commands and make output more readable
git-svn-id: svn+ssh://svn.mit.edu/athena/trunk@25794 728af825-273c-0410-89f9-f7d3b574a069

diff --git a/debathena/scripts/build-server/build-all/Makefile b/debathena/scripts/build-server/build-all/Makefile
--- a/debathena/scripts/build-server/build-all/Makefile
+++ b/debathena/scripts/build-server/build-all/Makefile
@@ -1,6 +1,6 @@
 suite := quantal
 psuite := quantal
-STAMPS := /afs/sipb.mit.edu/project/debathena/machines/awesome-build-server/stamps.$(suite)
+STAMPS := /afs/sipb.mit.edu/project/debathena/arch/amd64_deb40/bin/build-server/build-all/stamps/stamps.$(suite)
 
 package = $(STAMPS)/$(1).done
 
@@ -14,17 +14,22 @@ build/%: $(call package,%)
 	:
 
 $(call package,%):
-	file=$$(mktemp -t 'stupid.XXXXXX') && \
+	@echo "Starting build of $*"
+	@if [ -e $(STAMPS)/$*.started ]; then echo "Error, remove 'started' stamp and try again."; false; fi
+	@rm -f $(STAMPS)/$*.error
+	@file=$$(mktemp -t 'stupid.XXXXXX') && \
 		echo "screen sh -c '$(CURDIR)/do-build $* $(STAMPS)/$* $(suite) $(psuite)'" > "$$file" && \
 		echo "other" >> "$$file" && \
 		screen -X source "$$file" && \
 		sleep 2 && \
 		rm -f "$$file"
-	[ -e $(STAMPS)/$*.started ]
-	while ! [ -e $(STAMPS)/$*.done ] && ! [ -e $(STAMPS)/$*.error ]; do sleep 1; done
-	rm -f $(STAMPS)/$*.started
-	rm -f $(STAMPS)/$*.error
-	[ -e $(STAMPS)/$*.done ]
+	@[ -e $(STAMPS)/$*.started ]
+	@echo -n "Building $*..."
+	@while ! [ -e $(STAMPS)/$*.done ] && ! [ -e $(STAMPS)/$*.error ]; do sleep 1; done
+	@if [ -e $(STAMPS)/$*.done ]; then echo "OK"; else echo "FAILED"; fi
+	@rm -f $(STAMPS)/$*.started
+	@rm -f $(STAMPS)/$*.error
+	@[ -e $(STAMPS)/$*.done ]
 
 clean:
 	rm -f deps.mk $(STAMPS)/*.started $(STAMPS)/*.error
