In ssl-certificates:   * Let the MIT CA be managed by update-ca-certificates.  (This causes the     CA to be added to /etc/ssl/certs/ca-certificates.crt, and also lets     Java use the CA.)
git-svn-id: svn+ssh://svn.mit.edu/athena/trunk@23461 728af825-273c-0410-89f9-f7d3b574a069

diff --git a/debathena/config/ssl-certificates/debian/debathena-ssl-certificates.prerm b/debathena/config/ssl-certificates/debian/debathena-ssl-certificates.prerm
--- a/debathena/config/ssl-certificates/debian/debathena-ssl-certificates.prerm
+++ b/debathena/config/ssl-certificates/debian/debathena-ssl-certificates.prerm
@@ -1,43 +1,45 @@
 #!/bin/sh
-# postinst script for debathena-ssl-certificates
+# prerm script for debathena-ssl-certificates
 #
 # see: dh_installdeb(1)
 
 set -e
 
 # summary of how this script can be called:
-#        * <postinst> `configure' <most-recently-configured-version>
-#        * <old-postinst> `abort-upgrade' <new version>
-#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
-#          <new-version>
-#        * <postinst> `abort-remove'
-#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
-#          <failed-install-package> <version> `removing'
+#        * <prerm> `remove'
+#        * <old-prerm> `upgrade' <new-version>
+#        * <new-prerm> `failed-upgrade' <old-version>
+#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
+#        * <deconfigured's-prerm> `deconfigure' `in-favour'
+#          <package-being-installed> <version> `removing'
 #          <conflicting-package> <version>
 # for details, see http://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
 
 case "$1" in
-    configure)
+    remove|deconfigure)
 	perl -0pe '
 s/^### BEGIN debathena-ssl-certificates\n.*?^### END debathena-ssl-certificates\n//msg;
 s/\n?$/\n### BEGIN debathena-ssl-certificates
 # This section is automatically added by the debathena-ssl-certificates
 # package.
-mit.edu\/mitCAclient.crt
-mit.edu\/mitCA.crt
+!mit.edu\/mitCAclient.crt
+!mit.edu\/mitCA.crt
 ### END debathena-ssl-certificates
 /;
 ' -i /etc/ca-certificates.conf
 	update-ca-certificates
+	perl -0pe '
+s/^### BEGIN debathena-ssl-certificates\n.*?^### END debathena-ssl-certificates\n//msg;
+' -i /etc/ca-certificates.conf
     ;;
 
-    abort-upgrade|abort-remove|abort-deconfigure)
+    upgrade|failed-upgrade)
     ;;
 
     *)
-        echo "postinst called with unknown argument \`$1'" >&2
+        echo "prerm called with unknown argument \`$1'" >&2
         exit 1
     ;;
 esac
