In auto-update:   * Check for new flag file from license-config when reconfiguring
git-svn-id: svn+ssh://svn.mit.edu/athena/trunk@25049 728af825-273c-0410-89f9-f7d3b574a069

diff --git a/debathena/config/auto-update/debian/athena-auto-update b/debathena/config/auto-update/debian/athena-auto-update
--- a/debathena/config/auto-update/debian/athena-auto-update
+++ b/debathena/config/auto-update/debian/athena-auto-update
@@ -256,28 +256,32 @@ if ! v aptitude --quiet --assume-yes update; then
   exit
 fi
 
-# Update debathena-license-config and reconfigure any packages if necessary
+# Update debathena-license-config 
 pattern='^0 packages upgraded, 0 newly installed, 0 to remove'
 licenses=/usr/share/debathena-license-config/debathena-license-selections
 if ! v aptitude --simulate --assume-yes install debathena-license-config | grep -q "$pattern"; then
-  if v aptitude --assume-yes install debathena-license-config; then
-      if [ -f $licenses ]; then
-	  for p in $(awk '{print $1}' $licenses); do
-	      if dpkg-query --showformat '${Status}\n' -W $p 2>/dev/null | grep -q ' installed$'; then
-		  if ! v dpkg-reconfigure -fnoninteractive $p; then
-		      # Don't fail here
-		      complain "Failed to dpkg-reconfigure $p"
-		  fi
-	      fi
-	  done
-      else
-	  complain "Could not find $licenses"
-	  exit
-      fi
-  else
+  if ! v aptitude --assume-yes install debathena-license-config; then
       complain "Failed to update debathena-license-config"
       exit
   fi
+fi
+
+# If new licenses were installed, deal.
+if [ -f /var/lib/debathena-license-config/reconfigure_required ]; then
+    rm -f /var/lib/debathena-license-config/reconfigure_require
+    if [ -f $licenses ]; then
+	for p in $(awk '{print $1}' $licenses); do
+	    if dpkg-query --showformat '${Status}\n' -W $p 2>/dev/null | grep -q ' installed$'; then
+		if ! v dpkg-reconfigure -fnoninteractive $p; then
+		      # Don't fail here
+		    complain "Failed to dpkg-reconfigure $p"
+		fi
+	    fi
+	done
+    else
+	complain "Could not find $licenses"
+	exit
+    fi
 fi
 
 
