In auto-update:   * Actually, don't bother cleaning up the headers by hand.  Instead, just     auto-remove packages (unless that would remove metapackages) for     compatibility with old aptitude-based updater.  (Trac: #1012)   * Convert from CDBS to dh7 and build-dep on dh 7.0.50   * Update copyright file to format 1.0 and re-license under BSD 3-clause   * Bump Standards-Version to 3.9.3   * Remove unneeded dependency on bsdutils (it's required)   * Add $remote_fs dependency in init script because it's apparently still     1992 and /usr might be an NFS mount
git-svn-id: svn+ssh://svn.mit.edu/athena/trunk@25859 728af825-273c-0410-89f9-f7d3b574a069

diff --git a/debathena/config/auto-update/debian/athena-auto-update b/debathena/config/auto-update/debian/athena-auto-update
--- a/debathena/config/auto-update/debian/athena-auto-update
+++ b/debathena/config/auto-update/debian/athena-auto-update
@@ -342,7 +342,6 @@ if [ "$CLEANUP_OLD_KERNELS" = "yes" ]; then
     for k in $toremove; do
       if [ "$(uname -r)" != "$k" ]; then
         kpkgs="$kpkgs linux-image-$k"
-	khpkgs="$khpkgs linux-headers-$k"
       fi
     done
     echo "Will remove these kernels: $kpkgs"
@@ -355,17 +354,21 @@ if [ "$CLEANUP_OLD_KERNELS" = "yes" ]; then
     else
 	warn "Simulation failed!"
     fi
-    echo "Removing corresponding headers: $khpkgs"
-    echo "Simulating..."
-    if v apt-get -y -s remove $khpkgs; then
-      echo "Simulation ok, proceeding..."
-      if ! v apt-get -y remove $khpkgs; then
-	warn "Something went wrong trying to remove kernels!"
-      fi
-    else
-	warn "Simulation failed!"
-    fi
   fi
+fi
+
+# Auto-remove packages
+echo "Attempting to auto-remove old packages"
+echo "Simulating..."
+AUTOREMOVE="$(apt-get --assume-yes --simulate autoremove)"
+if [ $? -ne 0 ]; then
+    warn "Auto-remove simulation failed!"
+elif echo "$AUTOREMOVE" | egrep -q '^Remv debathena-(cluster|workstation|login-graphical|login|standard|auto-update) '; then
+    warn "Metapackages would be removed by auto-remove!"
+else
+    if ! v apt-get -y autoremove; then 
+	complain "Auto-remove failed even though simulation succeeded (shouldn't happen)"
+    fi
 fi
 
 # Finally, update the apt-file cache
