Propagate a cfields fix from the 8.0 tree: Clean up a loose end. xlogin should be restarted when it exits with nonzero status. If this script doesn't do it, xdm takes it as a sign to pop up its own login system. So restart xlogin appropriately, being sure to avoid an infinite loop if there are real problems.
git-svn-id: svn+ssh://svn.mit.edu/athena/trunk@9146 728af825-273c-0410-89f9-f7d3b574a069

diff --git a/athena/etc/xdm/xdm-sgi/Xlogin b/athena/etc/xdm/xdm-sgi/Xlogin
--- a/athena/etc/xdm/xdm-sgi/Xlogin
+++ b/athena/etc/xdm/xdm-sgi/Xlogin
@@ -43,7 +43,26 @@ for screen in $screens
 # also, "-f" in clogin means grab input focus
 if [ -x /etc/athena/xlogin ] ; then
 	/etc/athena/nanny -xup
-	exec /etc/athena/xlogin -config /etc/athena/login -display :0.0
+	# If xlogin exits with nonzero status three times within
+	# ten seconds, stop trying to run it. We use a low-tech
+	# time comparison and counter.
+	while true; do
+		sleep 10 &
+		sleeper=$!	
+		if /etc/athena/xlogin -config /etc/athena/login -display :0.0;
+			then exit 0
+		fi
+		if /etc/athena/xlogin -config /etc/athena/login -display :0.0;
+			then exit 0
+		fi
+		if /etc/athena/xlogin -config /etc/athena/login -display :0.0;
+			then exit 0
+		fi
+		if kill -0 $sleeper 2>/dev/null ;
+			then exit 1
+		fi
+		wait
+	done
 fi
 
 if /etc/chkconfig visuallogin ; then
