Reindent.
git-svn-id: svn+ssh://svn.mit.edu/athena/trunk@18882 728af825-273c-0410-89f9-f7d3b574a069

diff --git a/packs/build/rpm/build-all b/packs/build/rpm/build-all
--- a/packs/build/rpm/build-all
+++ b/packs/build/rpm/build-all
@@ -13,27 +13,27 @@ nobuild=false
 log=false
 
 while getopts s:d:knl opt; do
-	case "$opt" in
-	s)
-		source="$OPTARG"
-		;;
-	d)
-		destdir="$OPTARG"
-		;;
-	k)
-		ignore=true
-		;;
-	n)
-		nobuild=true
-		;;
-	l)
-		log=true
-		;;
-	\?)
-		echo "$usage"
-		exit 1
-		;;
-	esac
+  case "$opt" in
+  s)
+    source="$OPTARG"
+    ;;
+  d)
+    destdir="$OPTARG"
+    ;;
+  k)
+    ignore=true
+    ;;
+  n)
+    nobuild=true
+    ;;
+  l)
+    log=true
+    ;;
+  \?)
+    echo "$usage"
+    exit 1
+    ;;
+  esac
 done
 
 shift `expr $OPTIND - 1`
@@ -42,41 +42,41 @@ end="${2-$1}"
 
 case `uname -s` in
 Linux)
-	os=linux
-	awk=awk
-	;;
+  os=linux
+  awk=awk
+  ;;
 SunOS)
-	os=solaris
-	awk=nawk
-	;;
+  os=solaris
+  awk=nawk
+  ;;
 *)
-	echo "Unrecognized system type, aborting." >&2
-	exit 1
-	;;
+  echo "Unrecognized system type, aborting." >&2
+  exit 1
+  ;;
 esac
 
 # Send all output from this point on to the build log file.
 if [ true = "$log" ]; then
-	mkdir -p "$destdir/logs" 2>/dev/null
-	now=`date '+%y.%m.%d.%H'`
-	logfile=$destdir/logs/washlog.$now
-	rm -f "$destdir/logs/current"
-	ln -s "washlog.$now" "$destdir/logs/current"
-	exec >> "$logfile" 2>&1
+  mkdir -p "$destdir/logs" 2>/dev/null
+  now=`date '+%y.%m.%d.%H'`
+  logfile=$destdir/logs/washlog.$now
+  rm -f "$destdir/logs/current"
+  ln -s "washlog.$now" "$destdir/logs/current"
+  exec >> "$logfile" 2>&1
 fi
 
 # Read in the list of packages, filtering for the operating system.
 # Each line of output from getpackages.awk looks something like
 #    third/afsbin athena-afs
 set -- `$awk -f $source/packs/build/getpackages.awk \
-	os="$os" pkgnames=1 start="$start" end="$end" \
-	$source/packs/build/packages` || exit 1
+  os="$os" pkgnames=1 start="$start" end="$end" \
+  $source/packs/build/packages` || exit 1
 
 case $nobuild in
 true)
-	echo $*
-	exit
-	;;
+  echo $*
+  exit
+  ;;
 esac
 
 echo ========
@@ -84,26 +84,26 @@ echo Starting at `date` on $os
 
 # Build the packages
 while [ $# -ge 2 ]; do
-	echo "***** $1"
-	$source/packs/build/rpm/build-package -s $source -d $destdir $1 $2
-	if [ $? -ne 0 ]; then
-		echo "We bombed in $1"
-		if [ false = "$ignore" ]; then
-			exit 1
-		fi
-	fi
+  echo "***** $1"
+  $source/packs/build/rpm/build-package -s $source -d $destdir $1 $2
+  if [ $? -ne 0 ]; then
+    echo "We bombed in $1"
+    if [ false = "$ignore" ]; then
+      exit 1
+    fi
+  fi
 
-	# Redo the output redirection command to flush the log file.
-	if [ true = "$log" ]; then
-		exec >> "$logfile" 2>&1
-	fi
+  # Redo the output redirection command to flush the log file.
+  if [ true = "$log" ]; then
+    exec >> "$logfile" 2>&1
+  fi
 
-	shift 2
+  shift 2
 done
 
 if [ $# -ne 0 ]; then
-	echo "Extra grot at end of packages list:"
-	echo "$*"
+  echo "Extra grot at end of packages list:"
+  echo "$*"
 fi
 
 echo "Ending at `date`"
