Add Solaris support.
git-svn-id: svn+ssh://svn.mit.edu/athena/trunk@17953 728af825-273c-0410-89f9-f7d3b574a069

diff --git a/packs/build/rpm/build-all b/packs/build/rpm/build-all
--- a/packs/build/rpm/build-all
+++ b/packs/build/rpm/build-all
@@ -45,8 +45,12 @@ Linux)
 	os=linux
 	awk=awk
 	;;
+SunOS)
+	os=solaris
+	awk=nawk
+	;;
 *)
-	echo "This script is only for Linux."
+	echo "Unrecognized system type, aborting." >&2
 	exit 1
 	;;
 esac
