In gdm-config:   * Don't fail in maintainer scripts, even if the Debian utilities are     stupid
git-svn-id: svn+ssh://svn.mit.edu/athena/trunk@25163 728af825-273c-0410-89f9-f7d3b574a069

diff --git a/debathena/config/gdm-config/debian/debathena-gdm-config.postinst b/debathena/config/gdm-config/debian/debathena-gdm-config.postinst
--- a/debathena/config/gdm-config/debian/debathena-gdm-config.postinst
+++ b/debathena/config/gdm-config/debian/debathena-gdm-config.postinst
@@ -85,7 +85,9 @@ case "$1" in
 
 	if [ -f /usr/share/xsessions/athena.desktop ] && \
 	   [ -x /usr/lib/gdm/gdm-set-default-session ]; then
-	    /usr/lib/gdm/gdm-set-default-session -k athena
+	  # Sigh.  This exits non-zero if there already is a default 
+	  # session, but only if DBus is running.
+	  /usr/lib/gdm/gdm-set-default-session -k athena || true
 	fi
 
         if test -f /var/run/gdm.pid ; then
diff --git a/debathena/config/gdm-config/debian/debathena-gdm-config.prerm b/debathena/config/gdm-config/debian/debathena-gdm-config.prerm
--- a/debathena/config/gdm-config/debian/debathena-gdm-config.prerm
+++ b/debathena/config/gdm-config/debian/debathena-gdm-config.prerm
@@ -23,7 +23,9 @@ case "$1" in
             /usr/share/gdm/themes/debathena/metapackage-unknown.svg
 	if [ -f /usr/share/xsessions/athena.desktop ] && \
 	   [ -x /usr/lib/gdm/gdm-set-default-session ]; then
-	    /usr/lib/gdm/gdm-set-default-session -r athena
+	  # Sigh.  This exits non-zero if there already is a default 
+	  # session, but only if DBus is running.
+	  /usr/lib/gdm/gdm-set-default-session -r athena || true
 	fi
 
     ;;
