This commit was generated by cvs2svn to compensate for changes in r18907, which included commits to RCS files with non-trunk default branches.
git-svn-id: svn+ssh://svn.mit.edu/athena/trunk@18908 728af825-273c-0410-89f9-f7d3b574a069

diff --git a/third/tetex/src/texk/dviljk/dvihp b/third/tetex/src/texk/dviljk/dvihp
--- a/third/tetex/src/texk/dviljk/dvihp
+++ b/third/tetex/src/texk/dviljk/dvihp
@@ -1,17 +1,23 @@
 #!/bin/sh
-# $Id: dvihp,v 1.1.1.1 2000-03-10 17:51:51 ghudson Exp $
+# $Id: dvihp,v 1.1.1.2 2003-02-25 22:06:12 amb Exp $
 # Run dvicopy, then dvilj[k].  kb@mail.tug.org, 1994.  Public domain.
 # Try to accept arguments a la dvips, from Thomas Esser.
 
 : ${DVILJ=dvilj4}       # the dvilj variant to run
 : ${SPOOL=lpr}          # used to print an LJ file
-: ${TMPDIR=/tmp}        # for the dvicopy output
+: ${TMP=/tmp}        # for the dvicopy output
 
-TMPDIR=${TMPDIR}/dvihp$$
-mkdir $TMPDIR || { echo "cannot create directory \`$TMPDIR'."; exit 1; }
-trap 'cd /; rm -rf $TMPDIR; trap '' 0; exit 0' 0 1 2 3 6 7 13 15
+TMPDIR="${TMP}"/dvihp$$
+(umask 077; mkdir "$TMPDIR") \
+  || { echo "cannot create directory \`$TMPDIR'."; exit 1; }
 
-rcs_revision='$Revision: 1.1.1.1 $'
+trap '
+  cd "${TMP}"
+  test -d "$TMPDIR" && { rm -f "$TMPDIR"/*; rmdir "$TMPDIR"; }
+  exit 0
+' 0 1 2 3 6 7 13 15
+
+rcs_revision='$Revision: 1.1.1.2 $'
 version=`set - $rcs_revision; echo $2`
 
 usage="Usage: `basename $0` [OPTIONS] [DVIFILE[.dvi]].
@@ -94,19 +100,17 @@ while test $# -gt 0; do
 done
 
 # Make sure the filenames are unique on MS-DOS
-vfless_dvi=$TMPDIR/dvi$$.vf
-dvicopy_log=$TMPDIR/dvi$$.copy
-dvilj_log=$TMPDIR/dvi$$.lj
+vfless_dvi="$TMPDIR"/dvi$$.vf
 
 # Expand VF references.
 # If $infile is null, this will read standard input.
 # dvilj can't read from a pipe, so always write to a file.
 $verbose && echo "Running dvicopy $infile >$vfless_dvi" >&2
-if dvicopy $infile >$vfless_dvi; then :; else
+if dvicopy $infile >"$vfless_dvi"; then :; else
   echo "$0: dvicopy $infile failed." >&2
   exit 1
 fi
-$verbose && ls -l $vfless_dvi >&2
+$verbose && ls -l "$vfless_dvi" >&2
 
 if test -z "$output"; then
   output=- # output to stdout
@@ -118,11 +122,9 @@ else
 fi
 
 # Translate DVI to LJ.
-cmd="$DVILJ $opt $output_opt$output $vfless_dvi $maybe_spool_cmd"
+cmd="$DVILJ $opt $output_opt$output \"$vfless_dvi\" $maybe_spool_cmd"
 $verbose && echo "Running $cmd" >&2
 if eval $cmd; then :; else
   echo "$0: $DVILJ failed." >&2
   exit 2
 fi
-
-rm -f $TMPDIR/dvi$$.*
diff --git a/third/tetex/src/texk/kpathsea/mktexlsr b/third/tetex/src/texk/kpathsea/mktexlsr
--- a/third/tetex/src/texk/kpathsea/mktexlsr
+++ b/third/tetex/src/texk/kpathsea/mktexlsr
@@ -10,10 +10,10 @@
 # 'kpsestat', 'readlink', and 'kpsewhich' binaries.
 # 
 # Originally written as `texhash' by Thomas Esser
-# <te@informatik.uni-hannover.de>, Okt., 1994.
+# <te@dbs.uni-hannover.de>, Okt., 1994.
 # Public domain.
 
-version='$Id: mktexlsr,v 1.1.1.1 2000-03-10 17:51:27 ghudson Exp $'
+version='$Id: mktexlsr,v 1.1.1.2 2003-02-25 22:10:53 amb Exp $'
 progname=`echo $0 | sed 's%.*/%%'`
 usage="Usage: $progname [DIRS ...]
 
@@ -57,7 +57,7 @@ ls_R_magic='% ls-R -- filename database for kpathsea; do not change this line.'
 # The old string, which should continue to work.
 old_ls_R_magic='% ls-R -- maintained by MakeTeXls-R; do not change this line.'
 
-trap 'cd / ; rm -f "$db_file_tmp"; exit' 0 1 2 3 7 13 15
+trap 'cd / ; test -z "$db_dir_tmp" || rm -rf "$db_dir_tmp"; exit' 0 1 2 3 7 13 15
 
 test $# = 0 && {
   OIFS=$IFS; IFS=$SEP; set x `kpsewhich --show-path=ls-R 2>/dev/null`; shift; IFS=$OIFS
@@ -78,7 +78,6 @@ for TEXMFLS_R in "$@"; do
   *)  db_file="$TEXMFLS_R/$db_file"
   esac
   db_dir=`echo "$db_file" | sed 's%/[^/][^/]*$%%'` # can't rely on dirname
-  db_file_tmp="$db_dir/lsR$$.tmp"
 
   test -d "$db_dir" || continue
   test -w "$db_dir" || { echo "$progname: $db_dir: directory not writable. Skipping..." >&2; continue; }
@@ -87,8 +86,8 @@ for TEXMFLS_R in "$@"; do
     cp /dev/null "$db_file"
     # Use same permissions as parent directory, minus x,s, or t bits.
     chmod `kpsestat -xst "$db_dir"` "$db_file"
-  elif test "x`sed 1q \"$db_file\"`" != "x$ls_R_magic" \
-       && test "x`sed 1q \"$db_file\"`" != "x$old_ls_R_magic"; then
+  elif test "x`sed '1s/$//;1q' \"$db_file\"`" != "x$ls_R_magic" \
+       && test "x`sed '1s/$//;1q' \"$db_file\"`" != "x$old_ls_R_magic"; then
     echo "$progname: $db_file lacks magic string. Skipping..." >&2
     continue
   fi
@@ -96,6 +95,10 @@ for TEXMFLS_R in "$@"; do
   # Skip if we cannot write the file:
   access -w "$db_file" || { echo "$progname: $db_file: no write permission. Skipping..." >&2; continue; }
 
+  db_dir_tmp="$db_dir/lsR$$.tmp"
+  (umask 077 && mkdir "$db_dir_tmp" ) \
+    || { echo "$progname: could not create directory '$db_dir_tmp'. Skipping..." >&2; continue; }
+  db_file_tmp="$db_dir_tmp/lsR$$.tmp"
   rm -f "$db_file_tmp"
 
   tty -s && echo "$progname: Updating $db_file... "
@@ -115,6 +118,7 @@ for TEXMFLS_R in "$@"; do
   chmod $PERMS "$db_file_tmp"
   rm -f "$db_file"
   mv "$db_file_tmp" "$db_file"
+  rm -rf "$db_dir_tmp"
 done
 tty -s && echo "$progname: Done."
 exit 0
diff --git a/third/tetex/src/texk/tetex/configure b/third/tetex/src/texk/tetex/configure
--- a/third/tetex/src/texk/tetex/configure
+++ b/third/tetex/src/texk/tetex/configure
@@ -25,6 +25,8 @@ ac_help="$ac_help
 ac_help="$ac_help
   --without-mkofm-default      do not run mkofm if OFM file missing"
 ac_help="$ac_help
+  --with-mktexfmt-default      run mktexfmt if format file missing"
+ac_help="$ac_help
   --with-mktextex-default      run mktextex if TeX source missing"
 ac_help="$ac_help
   --enable-multiplatform     put executables in bin/PLATFORM"
@@ -539,6 +541,231 @@ fi
 
 
 
+# Extract the first word of "gcc", so it can be a program name with args.
+set dummy gcc; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:548: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_prog_CC'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  if test -n "$CC"; then
+  ac_cv_prog_CC="$CC" # Let the user override the test.
+else
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+  if test -z "$COMSPEC"; then ac_x=-f; else ac_x=-x; fi
+  ac_dummy="$PATH"
+  for ac_dir in $ac_dummy; do
+    test -z "$ac_dir" && ac_dir=.
+    if test $ac_x $ac_dir/$ac_word; then
+      ac_cv_prog_CC="gcc"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+fi
+fi
+CC="$ac_cv_prog_CC"
+if test -n "$CC"; then
+  echo "$ac_t""$CC" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+if test -z "$CC"; then
+  # Extract the first word of "cc", so it can be a program name with args.
+set dummy cc; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:579: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_prog_CC'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  if test -n "$CC"; then
+  ac_cv_prog_CC="$CC" # Let the user override the test.
+else
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+  ac_prog_rejected=no
+  if test -z "$COMSPEC"; then ac_x=-f; else ac_x=-x; fi
+  ac_dummy="$PATH"
+  for ac_dir in $ac_dummy; do
+    test -z "$ac_dir" && ac_dir=.
+    if test $ac_x $ac_dir/$ac_word; then
+      if test "$ac_dir/$ac_word" = "/usr/ucb/cc"; then
+        ac_prog_rejected=yes
+	continue
+      fi
+      ac_cv_prog_CC="cc"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+if test $ac_prog_rejected = yes; then
+  # We found a bogon in the path, so make sure we never use it.
+  set dummy $ac_cv_prog_CC
+  shift
+  if test $# -gt 0; then
+    # We chose a different compiler from the bogus one.
+    # However, it has the same basename, so the bogon will be chosen
+    # first if we set CC to just the basename; use the full file name.
+    shift
+    set dummy "$ac_dir/$ac_word" "$@"
+    shift
+    ac_cv_prog_CC="$@"
+  fi
+fi
+fi
+fi
+CC="$ac_cv_prog_CC"
+if test -n "$CC"; then
+  echo "$ac_t""$CC" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+  if test -z "$CC"; then
+    case "`uname -s`" in
+    *win32* | *WIN32*)
+      # Extract the first word of "cl", so it can be a program name with args.
+set dummy cl; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:631: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_prog_CC'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  if test -n "$CC"; then
+  ac_cv_prog_CC="$CC" # Let the user override the test.
+else
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+  if test -z "$COMSPEC"; then ac_x=-f; else ac_x=-x; fi
+  ac_dummy="$PATH"
+  for ac_dir in $ac_dummy; do
+    test -z "$ac_dir" && ac_dir=.
+    if test $ac_x $ac_dir/$ac_word; then
+      ac_cv_prog_CC="cl"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+fi
+fi
+CC="$ac_cv_prog_CC"
+if test -n "$CC"; then
+  echo "$ac_t""$CC" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+ ;;
+    esac
+  fi
+  test -z "$CC" && { echo "configure: error: no acceptable cc found in \$PATH" 1>&2; exit 1; }
+fi
+
+echo $ac_n "checking whether the C compiler ($CC $CFLAGS $LDFLAGS) works""... $ac_c" 1>&6
+echo "configure:664: checking whether the C compiler ($CC $CFLAGS $LDFLAGS) works" >&5
+
+ac_ext=c
+# CFLAGS is not in ac_cpp because -g, -O, etc. are not valid cpp options.
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='${CC-cc} -c $CFLAGS $CPPFLAGS conftest.$ac_ext 1>&5'
+ac_link='${CC-cc} -o conftest${ac_exeext} $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS 1>&5'
+cross_compiling=$ac_cv_prog_cc_cross
+
+cat > conftest.$ac_ext << EOF
+
+#line 675 "configure"
+#include "confdefs.h"
+
+main(){return(0);}
+EOF
+if { (eval echo configure:680: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  ac_cv_prog_cc_works=yes
+  # If we can't run a trivial program, we are probably using a cross compiler.
+  if (./conftest; exit) 2>/dev/null; then
+    ac_cv_prog_cc_cross=no
+  else
+    ac_cv_prog_cc_cross=yes
+  fi
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  ac_cv_prog_cc_works=no
+fi
+rm -fr conftest*
+ac_ext=c
+# CFLAGS is not in ac_cpp because -g, -O, etc. are not valid cpp options.
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='${CC-cc} -c $CFLAGS $CPPFLAGS conftest.$ac_ext 1>&5'
+ac_link='${CC-cc} -o conftest${ac_exeext} $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS 1>&5'
+cross_compiling=$ac_cv_prog_cc_cross
+
+echo "$ac_t""$ac_cv_prog_cc_works" 1>&6
+if test $ac_cv_prog_cc_works = no; then
+  { echo "configure: error: installation or configuration problem: C compiler cannot create executables." 1>&2; exit 1; }
+fi
+echo $ac_n "checking whether the C compiler ($CC $CFLAGS $LDFLAGS) is a cross-compiler""... $ac_c" 1>&6
+echo "configure:706: checking whether the C compiler ($CC $CFLAGS $LDFLAGS) is a cross-compiler" >&5
+echo "$ac_t""$ac_cv_prog_cc_cross" 1>&6
+cross_compiling=$ac_cv_prog_cc_cross
+
+echo $ac_n "checking whether we are using GNU C""... $ac_c" 1>&6
+echo "configure:711: checking whether we are using GNU C" >&5
+if eval "test \"`echo '$''{'ac_cv_prog_gcc'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  cat > conftest.c <<EOF
+#ifdef __GNUC__
+  yes;
+#endif
+EOF
+if { ac_try='${CC-cc} -E conftest.c'; { (eval echo configure:720: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }; } | egrep yes >/dev/null 2>&1; then
+  ac_cv_prog_gcc=yes
+else
+  ac_cv_prog_gcc=no
+fi
+fi
+
+echo "$ac_t""$ac_cv_prog_gcc" 1>&6
+
+if test $ac_cv_prog_gcc = yes; then
+  GCC=yes
+else
+  GCC=
+fi
+
+ac_test_CFLAGS="${CFLAGS+set}"
+ac_save_CFLAGS="$CFLAGS"
+CFLAGS=
+echo $ac_n "checking whether ${CC-cc} accepts -g""... $ac_c" 1>&6
+echo "configure:739: checking whether ${CC-cc} accepts -g" >&5
+if eval "test \"`echo '$''{'ac_cv_prog_cc_g'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  echo 'void f(){}' > conftest.c
+if test -z "`${CC-cc} -g -c conftest.c 2>&1`"; then
+  ac_cv_prog_cc_g=yes
+else
+  ac_cv_prog_cc_g=no
+fi
+rm -f conftest*
+
+fi
+
+echo "$ac_t""$ac_cv_prog_cc_g" 1>&6
+if test "$ac_test_CFLAGS" = set; then
+  CFLAGS="$ac_save_CFLAGS"
+elif test $ac_cv_prog_cc_g = yes; then
+  if test "$GCC" = yes; then
+    CFLAGS="-g -O2"
+  else
+    CFLAGS="-g"
+  fi
+else
+  if test "$GCC" = yes; then
+    CFLAGS="-O2"
+  else
+    CFLAGS=
+  fi
+fi
+
 ac_aux_dir=
 for ac_dir in $srcdir $srcdir/.. $srcdir/../..; do
   if test -f $ac_dir/install-sh; then
@@ -576,7 +803,7 @@ ac_configure=$ac_aux_dir/configure # This should be Cygnus configure.
 # SVR4 /usr/ucb/install, which tries to use the nonexistent group "staff"
 # ./install, which can be erroneously created by make from ./install.sh.
 echo $ac_n "checking for a BSD compatible install""... $ac_c" 1>&6
-echo "configure:580: checking for a BSD compatible install" >&5
+echo "configure:807: checking for a BSD compatible install" >&5
 if test -z "$INSTALL"; then
 if eval "test \"`echo '$''{'ac_cv_path_install'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -630,8 +857,31 @@ test -z "$INSTALL_SCRIPT" && INSTALL_SCRIPT='${INSTALL_PROGRAM}'
 
 test -z "$INSTALL_DATA" && INSTALL_DATA='${INSTALL} -m 644'
 
+echo $ac_n "checking whether ln -s works""... $ac_c" 1>&6
+echo "configure:862: checking whether ln -s works" >&5
+if eval "test \"`echo '$''{'ac_cv_prog_LN_S'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  rm -f conftestdata
+# MS-DOS is a special case, because it sort of pretends that ln -s
+# works for executables.
+if test -z "$COMSPEC" && ln -s X conftestdata 2>/dev/null
+then
+  rm -f conftestdata
+  ac_cv_prog_LN_S="ln -s"
+else
+  ac_cv_prog_LN_S=ln
+fi
+fi
+LN_S="$ac_cv_prog_LN_S"
+if test "$ac_cv_prog_LN_S" = "ln -s"; then
+  echo "$ac_t""yes" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
 echo $ac_n "checking whether ${MAKE-make} sets \${MAKE}""... $ac_c" 1>&6
-echo "configure:635: checking whether ${MAKE-make} sets \${MAKE}" >&5
+echo "configure:885: checking whether ${MAKE-make} sets \${MAKE}" >&5
 set dummy ${MAKE-make}; ac_make=`echo "$2" | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_prog_make_${ac_make}_set'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -657,33 +907,10 @@ else
   SET_MAKE="MAKE=${MAKE-make}"
 fi
 
-echo $ac_n "checking whether ln -s works""... $ac_c" 1>&6
-echo "configure:662: checking whether ln -s works" >&5
-if eval "test \"`echo '$''{'ac_cv_prog_LN_S'+set}'`\" = set"; then
-  echo $ac_n "(cached) $ac_c" 1>&6
-else
-  rm -f conftestdata
-# MS-DOS is a special case, because it sort of pretends that ln -s
-# works for executables.
-if test -z "$COMSPEC" && ln -s X conftestdata 2>/dev/null
-then
-  rm -f conftestdata
-  ac_cv_prog_LN_S="ln -s"
-else
-  ac_cv_prog_LN_S=ln
-fi
-fi
-LN_S="$ac_cv_prog_LN_S"
-if test "$ac_cv_prog_LN_S" = "ln -s"; then
-  echo "$ac_t""yes" 1>&6
-else
-  echo "$ac_t""no" 1>&6
-fi
-
 
 
 echo $ac_n "checking whether to enable maintainer-specific portions of Makefiles""... $ac_c" 1>&6
-echo "configure:687: checking whether to enable maintainer-specific portions of Makefiles" >&5
+echo "configure:914: checking whether to enable maintainer-specific portions of Makefiles" >&5
     # Check whether --enable-maintainer-mode or --disable-maintainer-mode was given.
 if test "${enable_maintainer_mode+set}" = set; then
   enableval="$enable_maintainer_mode"
@@ -702,7 +929,7 @@ fi
 
 
 echo $ac_n "checking for loader (symbol LD)""... $ac_c" 1>&6
-echo "configure:706: checking for loader (symbol LD)" >&5
+echo "configure:933: checking for loader (symbol LD)" >&5
 if eval "test \"`echo '$''{'cf_cv_subst_LD'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -716,7 +943,7 @@ echo "$ac_t""$LD" 1>&6
 
 
 echo $ac_n "checking for archiver (symbol AR)""... $ac_c" 1>&6
-echo "configure:720: checking for archiver (symbol AR)" >&5
+echo "configure:947: checking for archiver (symbol AR)" >&5
 if eval "test \"`echo '$''{'cf_cv_subst_AR'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -730,7 +957,7 @@ echo "$ac_t""$AR" 1>&6
 
 
 echo $ac_n "checking for archiver options (symbol ARFLAGS)""... $ac_c" 1>&6
-echo "configure:734: checking for archiver options (symbol ARFLAGS)" >&5
+echo "configure:961: checking for archiver options (symbol ARFLAGS)" >&5
 if eval "test \"`echo '$''{'cf_cv_subst_ARFLAGS'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -784,6 +1011,12 @@ else
   with_mkofm_default=yes
 fi
 
+# Check whether --with-mktexfmt-default or --without-mktexfmt-default was given.
+if test "${with_mktexfmt_default+set}" = set; then
+  withval="$with_mktexfmt_default"
+  :
+fi
+
 # Check whether --with-mktextex-default or --without-mktextex-default was given.
 if test "${with_mktextex_default+set}" = set; then
   withval="$with_mktextex_default"
@@ -800,7 +1033,7 @@ else { echo "configure: error: can not run $ac_config_sub" 1>&2; exit 1; }
 fi
 
 echo $ac_n "checking host system type""... $ac_c" 1>&6
-echo "configure:804: checking host system type" >&5
+echo "configure:1037: checking host system type" >&5
 
 host_alias=$host
 case "$host_alias" in
@@ -832,7 +1065,7 @@ fi
 
 
 echo $ac_n "checking where the main texmf tree is located""... $ac_c" 1>&6
-echo "configure:836: checking where the main texmf tree is located" >&5
+echo "configure:1069: checking where the main texmf tree is located" >&5
 texmfmain=
 if test "x$datadir" != 'x${prefix}/share'; then
   # First case, datadir is defined...
@@ -1024,11 +1257,12 @@ s%@includedir@%$includedir%g
 s%@oldincludedir@%$oldincludedir%g
 s%@infodir@%$infodir%g
 s%@mandir@%$mandir%g
+s%@CC@%$CC%g
 s%@INSTALL_PROGRAM@%$INSTALL_PROGRAM%g
 s%@INSTALL_SCRIPT@%$INSTALL_SCRIPT%g
 s%@INSTALL_DATA@%$INSTALL_DATA%g
-s%@SET_MAKE@%$SET_MAKE%g
 s%@LN_S@%$LN_S%g
+s%@SET_MAKE@%$SET_MAKE%g
 s%@MAINT@%$MAINT%g
 s%@LD@%$LD%g
 s%@AR@%$AR%g
