This commit was generated by cvs2svn to compensate for changes in r18557, which included commits to RCS files with non-trunk default branches.
git-svn-id: svn+ssh://svn.mit.edu/athena/trunk@18558 728af825-273c-0410-89f9-f7d3b574a069

diff --git a/third/ORBit2/configure.in b/third/ORBit2/configure.in
--- a/third/ORBit2/configure.in
+++ b/third/ORBit2/configure.in
@@ -15,8 +15,8 @@ LT_VERSION=0:0:0
 AC_SUBST(LT_VERSION)
 
 ORBIT_MAJOR_VERSION=2
-ORBIT_MINOR_VERSION=4
-ORBIT_MICRO_VERSION=4
+ORBIT_MINOR_VERSION=6
+ORBIT_MICRO_VERSION=0
 ORBIT_VERSION=$ORBIT_MAJOR_VERSION.$ORBIT_MINOR_VERSION.$ORBIT_MICRO_VERSION
 AC_SUBST(ORBIT_MAJOR_VERSION)
 AC_SUBST(ORBIT_MINOR_VERSION)
@@ -90,22 +90,36 @@ for test_indent in "$use_indent" "indent -" cat; do
   fi
 done
 AC_MSG_RESULT($INDENT_COMMAND)
-AC_DEFINE_UNQUOTED(INDENT_COMMAND,"$INDENT_COMMAND")
+AC_DEFINE_UNQUOTED(INDENT_COMMAND,"$INDENT_COMMAND",
+                   [command used for indentation])
 
 
 AC_ARG_ENABLE(purify, [  --enable-purify        be clean for memory debuggers], enable_purify=yes, enable_purify=no)
 if test z$enable_purify = zyes; then
-	AC_DEFINE(ORBIT_PURIFY)
+	AC_DEFINE(ORBIT_PURIFY, 1, [defined if purify is enabled])
 fi
 
 AC_PROG_AWK
 
 GLIB_REQUIRED=2.0.0
-LINC_REQUIRED=0.5.0
+LINC_REQUIRED=1.0.0
 LIBIDL_REQUIRED=0.7.4
 AC_SUBST(GLIB_REQUIRED)
 AC_SUBST(LINC_REQUIRED)
 AC_SUBST(LIBIDL_REQUIRED)
+
+dnl Check for pkg-config version; want >= 0.14.0 because of -pthread bug
+AC_PATH_PROG(PKG_CONFIG, pkg-config, no)
+if test "$PKG_CONFIG" = "no" ; then
+     echo "*** The pkg-config script could not be found. Make sure it is"
+     echo "*** in your path, or set the PKG_CONFIG environment variable"
+     echo "*** to the full path to pkg-config."
+     echo "*** Or see http://www.freedesktop.org/software/pkgconfig to get pkg-config."
+fi
+PKG_CONFIG_MIN_VERSION=0.14.0
+if ! $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
+  AC_MSG_ERROR(You need at least version $PKG_CONFIG_MIN_VERSION of pkg-config)
+fi
 
 dnl Checks for libraries.
 PKG_CHECK_MODULES(ORBIT, \
@@ -216,6 +230,7 @@ ORBit-CosNaming-2.0.pc
 ORBit.spec
 src/Makefile
 src/idl-compiler/Makefile
+src/idl-compiler/ORBit-idl-2.0.pc
 src/idl/Makefile
 src/idl/CORBA/Makefile
 src/idl/CORBA_PIDL/Makefile
@@ -230,6 +245,7 @@ src/orb/dynamic/Makefile
 src/orb/poa/Makefile
 src/services/Makefile
 src/services/name/Makefile
+src/services/imodule/Makefile
 include/Makefile
 include/orbit/Makefile
 include/orbit/orbit-config.h
