Import of perl 5.004_04
git-svn-id: svn+ssh://svn.mit.edu/athena/branches/vendor@10723 728af825-273c-0410-89f9-f7d3b574a069

diff --git a/third/perl/x2p/Makefile.SH b/third/perl/x2p/Makefile.SH
--- a/third/perl/x2p/Makefile.SH
+++ b/third/perl/x2p/Makefile.SH
@@ -1,46 +1,38 @@
-case "$0" in
-*/*) cd `expr X$0 : 'X\(.*\)/'` ;;
-esac
 case $CONFIG in
 '')
-    if test ! -f config.sh; then
-	ln ../config.sh . || \
-	ln -s ../config.sh . || \
-	ln ../../config.sh . || \
-	ln ../../../config.sh . || \
-	(echo "Can't find config.sh."; exit 1)
-    fi 2>/dev/null
-    . ./config.sh
-    ;;
+	if test -f config.sh; then TOP=.;
+	elif test -f ../config.sh; then TOP=..;
+	elif test -f ../../config.sh; then TOP=../..;
+	elif test -f ../../../config.sh; then TOP=../../..;
+	elif test -f ../../../../config.sh; then TOP=../../../..;
+	else
+		echo "Can't find config.sh."; exit 1
+	fi
+	. $TOP/config.sh
+	;;
 esac
+: This forces SH files to create target in same directory as SH file.
+: This is so that make depend always knows where to find SH derivatives.
+case "$0" in
+*/Makefile.SH) cd `expr X$0 : 'X\(.*\)/'` ;;
+Makefile.SH) ;;
+*) case `pwd` in
+   */x2p) ;;
+   *) if test -d x2p; then cd x2p
+      else echo "Can't figure out where to write output."; exit 1
+	  fi;;
+   esac;;
+esac
+
 echo "Extracting x2p/Makefile (with variable substitutions)"
 rm -f Makefile
 cat >Makefile <<!GROK!THIS!
-# $RCSfile: Makefile.SH,v $$Revision: 1.1.1.1 $$Date: 1996-10-02 06:40:21 $
+# $RCSfile: Makefile.SH,v $$Revision: 1.1.1.2 $$Date: 1997-11-13 01:50:09 $
 #
 # $Log: not supported by cvs2svn $
-# Revision 4.0.1.3  92/06/08  16:11:32  lwall
-# patch20: SH files didn't work well with symbolic links
-# patch20: cray didn't give enough memory to /bin/sh
-# patch20: makefiles now display new shift/reduce expectations
-# 
-# Revision 4.0.1.2  91/11/05  19:19:04  lwall
-# patch11: random cleanup
-# 
-# Revision 4.0.1.1  91/06/07  12:12:14  lwall
-# patch4: cflags now emits entire cc command except for the filename
-# 
-# Revision 4.0  91/03/20  01:57:03  lwall
-# 4.0 baseline.
-# 
-# 
 
 CC = $cc
-YACC = $yacc
-bin = $bin
-lib = $lib
-mansrc = $mansrc
-manext = $manext
+BYACC = $byacc
 LDFLAGS = $ldflags
 SMALL = $small
 LARGE = $large $split
@@ -49,6 +41,23 @@ mallocobj = $mallocobj
 shellflags = $shellflags
 
 libs = $libs
+
+$make_set_make
+# grrr
+SHELL = $sh
+
+# These variables will be used in a future version to make
+# the make file more portable to non-unix systems.
+AR = $ar
+EXE_EXT = $exe_ext
+LIB_EXT = $lib_ext
+OBJ_EXT = $obj_ext
+PATH_SEP = $path_sep
+
+FIRSTMAKEFILE = $firstmakefile
+
+.SUFFIXES: .c \$(OBJ_EXT)
+
 !GROK!THIS!
 
 cat >>Makefile <<'!NO!SUBS!'
@@ -63,59 +72,56 @@ manpages = a2p.man s2p.man
 
 util =
 
-sh = Makefile.SH makedepend.SH
+sh = Makefile.SH cflags.SH
+shextract = Makefile cflags
 
-h = EXTERN.h INTERN.h ../config.h handy.h hash.h a2p.h str.h util.h
+pl = find2perl.PL s2p.PL
+plextract = find2perl s2p
+
+addedbyconf = $(shextract) $(plextract)
+
+h = EXTERN.h INTERN.h ../config.h ../handy.h hash.h a2p.h str.h util.h
 
 c = hash.c $(mallocsrc) str.c util.c walk.c
 
-obj = hash.o $(mallocobj) str.o util.o walk.o
+obj = hash$(OBJ_EXT) $(mallocobj) str$(OBJ_EXT) util$(OBJ_EXT) walk$(OBJ_EXT)
 
 lintflags = -phbvxac
 
-addedbyconf = Makefile.old bsd eunice filexp loc pdp11 usg v7
 
-# grrr
-SHELL = /bin/sh
-
-.c.o:
-	$(CCCMD) $*.c
+.c$(OBJ_EXT):
+	$(CCCMD) -DPERL_FOR_X2P $*.c
 
 all: $(public) $(private) $(util)
 	touch all
 
-a2p: $(obj) a2p.o
-	$(CC) $(LDFLAGS) $(obj) a2p.o $(libs) -o a2p
+a2p: $(obj) a2p$(OBJ_EXT)
+	$(CC) $(LDFLAGS) $(obj) a2p$(OBJ_EXT) $(libs) -o a2p
 
-a2p.c: a2p.y
-	@ echo Expect 231 shift/reduce conflicts...
-	$(YACC) a2p.y
+# I now supply a2p.c with the kits, so the following section is
+# used only if you force byacc to run by saying
+# make  run_byacc
+
+run_byacc:	FORCE
+	@ echo Expect many shift/reduce and reduce/reduce conflicts
+	$(BYACC) a2p.y
 	mv y.tab.c a2p.c
 
-a2p.o: a2p.c a2py.c a2p.h EXTERN.h util.h INTERN.h handy.h ../config.h str.h hash.h
+# We don't want to regenerate a2p.c, but it might appear out-of-date
+# after a patch is applied or a new distribution is made.
+a2p.c: a2p.y
+	-@touch a2p.c
+
+a2p$(OBJ_EXT): a2p.c a2py.c a2p.h EXTERN.h util.h INTERN.h \
+		../handy.h ../config.h str.h hash.h
 	$(CCCMD) $(LARGE) a2p.c
 
-install: a2p s2p
-# won't work with csh
-	export PATH || exit 1
-	- mv $(bin)/a2p $(bin)/a2p.old 2>/dev/null
-	- mv $(bin)/s2p $(bin)/s2p.old 2>/dev/null
-	- if test `pwd` != $(bin); then cp $(public) $(bin); fi
-	cd $(bin); \
-for pub in $(public); do \
-chmod +x `basename $$pub`; \
-done
-	- if test `pwd` != $(mansrc); then \
-for page in $(manpages); do \
-cp $$page $(mansrc)/`basename $$page .man`.$(manext); \
-done; \
-fi
-
 clean:
-	rm -f a2p *.o a2p.c
+	rm -f a2p *$(OBJ_EXT)
 
 realclean: clean
-	rm -f *.orig */*.orig core $(addedbyconf) a2p.c s2p find2perl all cflags
+	rm -f *.orig core $(addedbyconf) all malloc.c
+	rm -f $(FIRSTMAKEFILE) $(FIRSTMAKEFILE).old
 
 # The following lint has practically everything turned on.  Unfortunately,
 # you have to wade through a lot of mumbo jumbo that can't be suppressed.
@@ -126,7 +132,7 @@ lint:
 	lint $(lintflags) $(defs) $(c) > a2p.fuzz
 
 depend: $(mallocsrc) ../makedepend
-	../makedepend
+	sh ../makedepend MAKE=$(MAKE)
 
 clist:
 	echo $(c) | tr ' ' '\012' >.clist
@@ -137,24 +143,28 @@ hlist:
 shlist:
 	echo $(sh) | tr ' ' '\012' >.shlist
 
-config.sh: ../config.sh
-	rm -f config.sh
-	ln ../config.sh .
+# These should be automatically generated
+
+$(plextract):
+	../miniperl -I../lib $@.PL
 
 malloc.c: ../malloc.c
-	sed 's/"perl.h"/"..\/perl.h"/' ../malloc.c >malloc.c
+	rm -f malloc.c
+	sed <../malloc.c >malloc.c \
+	    -e 's/"EXTERN.h"/"..\/EXTERN.h"/' \
+	    -e 's/"perl.h"/"..\/perl.h"/' \
+	    -e 's/my_exit/exit/'
 
 # AUTOMATICALLY GENERATED MAKE DEPENDENCIES--PUT NOTHING BELOW THIS LINE
 $(obj):
 	@ echo "You haven't done a "'"make depend" yet!'; exit 1
-makedepend: makedepend.SH
-	/bin/sh $(shellflags) makedepend.SH
+makedepend: depend
 !NO!SUBS!
 $eunicefix Makefile
 case `pwd` in
 *SH)
     $rm -f ../Makefile
-    ln Makefile ../Makefile
+    $ln Makefile ../Makefile
     ;;
 esac
-rm -f makefile
+rm -f $firstmakefile
