This commit was generated by cvs2svn to compensate for changes in r20170, which included commits to RCS files with non-trunk default branches.
git-svn-id: svn+ssh://svn.mit.edu/athena/trunk@20171 728af825-273c-0410-89f9-f7d3b574a069

diff --git a/third/krb5/src/kadmin/testing/scripts/start_servers_local b/third/krb5/src/kadmin/testing/scripts/start_servers_local
--- a/third/krb5/src/kadmin/testing/scripts/start_servers_local
+++ b/third/krb5/src/kadmin/testing/scripts/start_servers_local
@@ -102,7 +102,9 @@ puts stdout [ovsec_kadm_create_principal $server_handle \
 puts stdout [ovsec_kadm_destroy $server_handle]
 EOF
 eval "$SRVTCL < /tmp/start_servers_local$$ $REDIRECT"
+x=$?
 rm /tmp/start_servers_local$$
+if test $x != 0 ; then exit 1 ; fi
 
 # rm -f /etc/v5srvtab
 # eval $LOCAL_MAKE_KEYTAB -princ host/xCANONHOSTx /etc/v5srvtab $REDIRECT
@@ -114,8 +116,14 @@ kdc_start_file=/tmp/kdc_server_start.$$
 
 rm -f $kdc_start_file
 
-(trap "" 2; cd $TOP/../kdc; ./krb5kdc; touch $kdc_start_file) \
-	< /dev/null > $usrtmp/kdc-log 2>&1 &
+if test "x$USER" = x ; then
+  USER=$LOGNAME ; export USER
+fi
+
+kdc_args="-R dfl:kdc_rcache.$USER"
+
+(trap "" 2; cd $TOP/../kdc; ./krb5kdc $kdc_args; touch $kdc_start_file) \
+	< /dev/null > $usrtmp/kdc-log.$USER 2>&1 &
 
 s=10
 max_s=60
@@ -126,7 +134,7 @@ while true; do
 	rm -f $adm_start_file
 
 	(sleep 5; cd $TOP/server; ./kadmind $ovadm_args; \
-		touch $adm_start_file) < /dev/null > $usrtmp/kadm-log 2>&1 &
+		touch $adm_start_file) < /dev/null > $usrtmp/kadm-log.$USER 2>&1 &
 
 	# wait until they start
 
@@ -154,7 +162,10 @@ while true; do
 		fi
 		if $EXPECT <<EOF
 		$LOG_USER
-		spawn telnet localhost 1751
+#		spawn telnet localhost 1751
+# Connect to 127.0.0.1 explicitly, so failure to connect to ::1 will not
+# cause bogus errors.
+		spawn telnet 127.0.0.1 1751
 		expect {
 			"Connection refused" {
 				close
diff --git a/third/krb5/src/util/reconf b/third/krb5/src/util/reconf
--- a/third/krb5/src/util/reconf
+++ b/third/krb5/src/util/reconf
@@ -1,8 +1,11 @@
 #!/bin/sh
 
 force=
-autoreconfprog=./util/autoconf/autoreconf
+autoreconfprog=autoreconf
+localdir=.
+autoreconfoptions=""
 verbose=false
+localdirarg=
 
 autoreconf="/bin/sh $autoreconfprog"
 
@@ -21,24 +24,77 @@ do
   esac
 done
 
+# Currently (2003-04-24) we need 2.52 or later.
+patb="2.(1[0-9][0-9])|(5[2-9])|([6-9][0-9])"
 
-if test ! -f $autoreconfprog ; then
-	if autoreconf --version | grep -q "version 2.[123456789]" && \
-	   autoconf --version  | grep -q "version 2.[123456789]" && \
-	   autoheader --version | grep -q "version 2.[123456789]" ; then
-		autoreconf=autoreconf
-		echo "Using" `autoconf --version` "found in your path..."
-	else
-		echo "Couldn't find autoconf 2.1 or higher in your path."
-		echo " "
-		echo "Please cd to util/autoconf, and type the commands"
-		echo "'configure' and then 'make'; then cd back to the top"
-		echo "of the source tree and re-run ./util/reconf"
-		exit 1
-	fi
+# sedcmd1 recognizes the older 2.12 version, and sedcmd2 the newer 2.49
+sedcmd1="s,.*version \(.*\)$,\1,"
+sedcmd2="s,.*) \(.*\)$,\1,;1q"
+
+if autoreconf --version | sed -e "$sedcmd1" -e "$sedcmd2" | egrep "$patb" >/dev/null && \
+    autoconf --version  | sed -e "$sedcmd1" -e "$sedcmd2"  | egrep "$patb" >/dev/null && \
+    autoheader --version | sed -e "$sedcmd1" -e "$sedcmd2" | egrep "$patb" >/dev/null; then
+    autoreconf=autoreconf
+    autoreconfoptions=
+    autoconfversion=`autoconf --version | sed -e "$sedcmd1" -e "$sedcmd2"`
+	echo "Using autoconf version $autoconfversion found in your path..."
+	localdir=`pwd`
+
+	# Determine if we need to patch autoreconf for 2.53
+	case "$autoconfversion" in
+	  2.52)
+	       echo "WARNING: autoconf 2.52 is known to generate buggy configure scripts!"
+	       ;;
+	  2.53)
+	       echo "Patching autoreconf"
+	       # Walk the path to find autoreconf
+	       autoreconfpath=
+	       for i in `echo $PATH | sed -e 's/:/ /g'` ; do
+		   if test -r $i/autoreconf; then
+		       autoreconfpath=$i/autoreconf
+		       break
+		   fi
+	       done
+	       if test "x$autoreconfpath" = "x" ; then 
+		   echo "Could not find autoreconf executable!!!"
+		   exit
+	       fi
+	       
+	       echo "About to patch $autoreconfpath to ..."
+	       TMPCMD=/tmp/autoreconf$$
+	       sed -e 's/push @ARGV, $_;/push @ARGV, catfile ($directory, $_);/' $autoreconfpath > $TMPCMD
+	       autoreconf="/bin/sh $TMPCMD"
+	       trap "rm $TMPCMD" 0
+	       ;;
+	  *)
+	       ;;
+	esac
+
+	# Determine the proper argument to autoreconf 
+	case "$autoconfversion" in
+	  2.1*)
+	       localdirarg="-l"
+	       ;;
+	  2.5[23])
+	       localdirarg="-l"
+	       ;;
+	    *)
+	       localdirarg="-I"
+	       ;;
+	esac
+else
+	echo "Couldn't find autoconf 2.52 or higher in your path."
+	echo " "
+	echo "Please install or add to your path and re-run ./util/reconf"
+	exit 1
 fi
 
 if $verbose ; then 
-	echo $autoreconf -m util/autoconf -l . --verbose $force 
+	echo $autoreconf $autoreconfoptions $localdirarg $localdir --verbose $force
 fi
-$autoreconf -m util/autoconf -l . --verbose $force 
+$autoreconf $autoreconfoptions  $localdirarg $localdir --verbose $force || exit 1
+if test $? = 0 ; then
+    if test ! -d include/krb5/autoconf.stmp ; then
+	cp /dev/null include/krb5/autoconf.stmp
+    fi
+fi
