Merge with krb5 1.4.1.
git-svn-id: svn+ssh://svn.mit.edu/athena/trunk@21895 728af825-273c-0410-89f9-f7d3b574a069

diff --git a/third/krb5/src/lib/gssapi/configure b/third/krb5/src/lib/gssapi/configure
--- a/third/krb5/src/lib/gssapi/configure
+++ b/third/krb5/src/lib/gssapi/configure
@@ -7199,7 +7199,120 @@ echo "${ECHO_T}$ac_cv_header_stdint_h" >&6
 fi
 if test $ac_cv_header_stdint_h = yes; then
 
-	include_stdint="\\#include <stdint.h>"
+	include_stdint='awk '\''END{printf("%cinclude <stdint.h>\n", 35);}'\'' < /dev/null'
+else
+  include_stdint='echo "/* no stdint.h */"'
+fi
+
+
+
+if test "${ac_cv_header_xom_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for xom.h" >&5
+echo $ECHO_N "checking for xom.h... $ECHO_C" >&6
+if test "${ac_cv_header_xom_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_xom_h" >&5
+echo "${ECHO_T}$ac_cv_header_xom_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking xom.h usability" >&5
+echo $ECHO_N "checking xom.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+$ac_includes_default
+#include <xom.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking xom.h presence" >&5
+echo $ECHO_N "checking xom.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <xom.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  egrep -v '^ *\+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: xom.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: xom.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: xom.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: xom.h: proceeding with the preprocessor's result" >&2;};;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: xom.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: xom.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: xom.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: xom.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: xom.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: xom.h: proceeding with the preprocessor's result" >&2;};;
+esac
+echo "$as_me:$LINENO: checking for xom.h" >&5
+echo $ECHO_N "checking for xom.h... $ECHO_C" >&6
+if test "${ac_cv_header_xom_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_xom_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_xom_h" >&5
+echo "${ECHO_T}$ac_cv_header_xom_h" >&6
+
+fi
+if test $ac_cv_header_xom_h = yes; then
+
+	include_xom='awk '\''END{printf("%cinclude <xom.h>\n", 35);}'\'' < /dev/null'
+else
+
+	include_xom='echo "/* no xom.h */"'
 fi
 
 
@@ -8364,6 +8477,7 @@ s,@PTHREAD_CFLAGS@,$PTHREAD_CFLAGS,;t t
 s,@AWK@,$AWK,;t t
 s,@EGREP@,$EGREP,;t t
 s,@include_stdint@,$include_stdint,;t t
+s,@include_xom@,$include_xom,;t t
 s,@OBJLISTS@,$OBJLISTS,;t t
 s,@STOBJEXT@,$STOBJEXT,;t t
 s,@SHOBJEXT@,$SHOBJEXT,;t t
