This commit was generated by cvs2svn to compensate for changes in r12208, which included commits to RCS files with non-trunk default branches.
git-svn-id: svn+ssh://svn.mit.edu/athena/trunk@12209 728af825-273c-0410-89f9-f7d3b574a069

diff --git a/third/tex/xdvi/MakeTeXPK b/third/tex/xdvi/MakeTeXPK
--- a/third/tex/xdvi/MakeTeXPK
+++ b/third/tex/xdvi/MakeTeXPK
@@ -1,20 +1,31 @@
 #!/bin/sh
 #
-#   This script file makes a new TeX PK font, because one wasn't
-#   found.  Parameters are:
+#   This script file makes a new TeX PK font, because one wasn't found.
 #
-#   name dpi bdpi magnification [mode [subdir]]
+#   It must echo the name of the generated PK file (and nothing else) to
+#   standard output or to the designated file descriptor.
+#   Yes, this is different from the original dvips.
 #
-#   `name' is the name of the font, such as `cmr10'.  `dpi' is
-#   the resolution the font is needed at.  `bdpi' is the base
-#   resolution, useful for figuring out the mode to make the font
-#   in.  `magnification' is a string to pass to MF as the
-#   magnification.  `mode', if supplied, is the mode to use.
+#   Parameters are:
+#
+#   name dpi bdpi magnification [mode [destdir [redirect]]]
+#
+#   `name'          is the name of the font, such as `cmr10'.
+#   `dpi'           is the resolution the font is needed at.
+#   `bdpi'          is the base resolution, useful for figuring out the mode to
+#                   make the font in.
+#   `magnification' is a string to pass to MF as the magnification.
+#   `mode'          (if supplied) is the mode to use.  If it's `default,'
+#                   then we guess.
+#   `destdir'       (if supplied) is the absolute directory name to use.
+#   `redirect'      (if supplied) is a string of the form '>&n', where n is the
+#                   number of the file descriptor which is to receive,
+#                   instead of stdout, the name of the newly created pk file.
 #
 #   Note that this file must execute Metafont, and then gftopk,
 #   and place the result in the correct location for the PostScript
 #   driver to find it subsequently.  If this doesn't work, it will
-#   be evident because MF will be invoked over and over again.
+#   be evident because this file will be invoked over and over again.
 #
 #   Of course, it needs to be set up for your site.
 #
@@ -75,8 +86,8 @@ then
    then
       MODE=linosuper
    else
-      echo "I don't know the mode for $BDPI"
-      echo "Have your system admin update MakeTeXPK"
+      echo "I don't know the mode for $BDPI" >&2
+      echo "Have your system admin update MakeTeXPK" >&2
       exit 1
    fi
 fi
@@ -86,9 +97,10 @@ fi
 GFNAME=$NAME.$DPI'gf'
 PKNAME=$NAME.$DPI'pk'
 
-# Clean up on normal or abnormal exit
-trap "cd /; /bin/rm -rf $TEMPDIR $DESTDIR/pktmp.$$" 0 1 2 15
-
+if test "$6" != ""
+then
+   DESTDIR="$6"
+fi
 
 if test ! -d $DESTDIR
 then
@@ -96,45 +108,44 @@ then
    chmod 777 $DESTDIR
 fi
 
-if test "$6" != ""
-then
-   DESTDIR=$DESTDIR"$6"
-   if test ! -d $DESTDIR
-   then
-      mkdir $DESTDIR
-      chmod 777 $DESTDIR
-   fi
+REDIRECT=
+if test -n "$7"; then
+  REDIRECT=`echo "$7" | sed 's/^>&//'`
+  if test `(cat /dev/null >&$REDIRECT) 2>&1 | wc -l` -ne 0; then
+    echo "$0: argument '$7' ignored - bad file number" >&2
+    REDIRECT=
+  fi
 fi
+
 
 # added by gwb, to allow searching in current dir before cd'ing
 if test "$MFINPUTS" != ""
 then
    MFINPUTS=$MFINPUTS:`pwd`; export MFINPUTS
 fi
+
+
+# Beginning of main function definition.
+generate()
+{
+
 mkdir $TEMPDIR
 cd $TEMPDIR
 
 if test -r $DESTDIR/$PKNAME
 then
    echo "$DESTDIR/$PKNAME already exists!"
+   showname $DESTDIR/$PKNAME
    exit 0
 fi
 
 # check also in the standard place
 
-if test "$6" = ""
+if test -r $TEXDIR/fonts/pk/$PKNAME
 then
-   if test -r $TEXDIR/fonts/pk/$PKNAME
-   then
-      echo $TEXDIR/fonts/pk/$PKNAME already exists!
-      exit 0
-   fi
-else
-   if test -r $TEXDIR/fonts/pk/$6"$PKNAME"
-   then
-      echo $TEXDIR/fonts/pk/$6"$PKNAME" already exists!
-      exit 0
-   fi
+   echo $TEXDIR/fonts/pk/$PKNAME already exists!
+   showname $TEXDIR/fonts/pk/$PKNAME
+   exit 0
 fi
 
 unset DISPLAY
@@ -155,5 +166,34 @@ mv $PKNAME $DESTDIR/pktmp.$$
 cd $DESTDIR
 mv pktmp.$$ $PKNAME
 chmod a+r $PKNAME
+showname $DESTDIR/$PKNAME
 
-exit 0
+}
+# end of main function definition
+
+
+if test -z "$REDIRECT"; then
+
+  showname()
+  {
+    echo "$@" > $TEMPDIR/mtout.$$
+  }
+
+  # Clean up on normal or abnormal exit.
+  trap 'cd /; test -f $TEMPDIR/mtout.$$ && cat $TEMPDIR/mtout.$$; rm -rf $TEMPDIR; trap "" 0; exit 0' 0 1 2 15
+
+  (generate) >&2
+
+else
+
+  showname()
+  {
+    echo "$@" >&$REDIRECT
+  }
+
+  # Clean up on normal or abnormal exit.
+  trap 'cd /; rm -rf $TEMPDIR; trap "" 0; exit 0' 0 1 2 15
+
+  generate
+
+fi
