This commit was generated by cvs2svn to compensate for changes in r18217, which included commits to RCS files with non-trunk default branches.
git-svn-id: svn+ssh://svn.mit.edu/athena/trunk@18218 728af825-273c-0410-89f9-f7d3b574a069

diff --git a/third/scrollkeeper/scripts/scrollkeeper-rebuilddb.in b/third/scrollkeeper/scripts/scrollkeeper-rebuilddb.in
--- a/third/scrollkeeper/scripts/scrollkeeper-rebuilddb.in
+++ b/third/scrollkeeper/scripts/scrollkeeper-rebuilddb.in
@@ -6,51 +6,47 @@ localstatedir=@localstatedir@
 usage()
 {
     cat <<EOF
-Usage: scrollkeeper-rebuilddb [-v] [-p <SCROLLKEEPER_DB_DIR>] 
+Usage: scrollkeeper-rebuilddb [-v] [-q] [-p <SCROLLKEEPER_DB_DIR>] 
 EOF
 
     exit $1
 }
 
-if test $# -ne 0 -a $# -ne 1 -a $# -ne 2 -a $# -ne 3; then
-        usage 1
-fi
 
-if test $# -eq 0; then # no flag
-    scrollkeeper_db_dir=`scrollkeeper-config --pkglocalstatedir`
-    verbose=""
+# Initialize variables with default setting
+scrollkeeper_db_dir=`scrollkeeper-config --pkglocalstatedir`
+verbose=""
+quiet=""
+
+while getopts "p:qv" opt; do
+    case $opt in
+    p ) scrollkeeper_db_dir=$OPTARG ;;
+    q ) quiet="-q" ;;
+    v ) verbose="-v" ;;
+    \? ) usage 1 ;;
+    esac
+done
+
+shift `expr $OPTIND - 1`
+
+datestring=`date +"%b %d %X"`
+if [ -z "$scrollkeeper_db_dir" ]; then 
+    echo "$datestring scrollkeeper-rebuilddb: Empty database path returned from scrollkeeper-config." >> @localstatedir@/log/scrollkeeper.log
+    echo "$datestring scrollkeeper-rebuilddb: Cannot rebuild ScrollKeeper database." >> @localstatedir@/log/scrollkeeper.log
+    if [ ! $quiet ] || [ $quiet != "-q" ]; then
+        echo "scrollkeeper-rebuilddb: Empty database path returned from scrollkeeper-config."
+        echo "scrollkeeper-rebuilddb: Cannot rebuild ScrollKeeper database."
+    fi
+    exit 1; 
 else
-    if test $# -eq 1; then # -v flag
-	if test $1 != "-v"; then
-	    usage 1
-	fi	
-	scrollkeeper_db_dir=`scrollkeeper-config --pkglocalstatedir`
-	verbose="-v"
-    fi
-    if test $# -eq 2; then # -p flag
-	if test $1 != "-p"; then
-            usage 1
-        fi
-	scrollkeeper_db_dir=$2
-	verbose=""
-    fi
-    if test $# -eq 3; then # -p and -v flag
-	if test $1 = "-v" -a $2 = "-p"; then 
-	    scrollkeeper_db_dir=$3
-	    verbose="-v"
-	else
-	    if test $1 = "-p" -a $3 = "-v"; then
-		scrollkeeper_db_dir=$2
-                verbose="-v"
-	    else
-	    	usage 1
-	    fi
-	fi
-    fi
+    rm -rf $scrollkeeper_db_dir
 fi
 
-rm -rf $scrollkeeper_db_dir/*
+echo "$datestring scrollkeeper-rebuilddb: Rebuilding ScrollKeeper database..." >> @localstatedir@/log/scrollkeeper.log
 
-scrollkeeper-update $verbose -p $scrollkeeper_db_dir
+scrollkeeper-update $quiet $verbose -p $scrollkeeper_db_dir
+
+datestring=`date +"%b %d %X"`
+echo "$datestring scrollkeeper-rebuilddb: Done rebuilding ScrollKeeper database." >> @localstatedir@/log/scrollkeeper.log
 
 exit 0
